/* ─── i18n Translations ──────────────────────────────────────────── */
const LANG = {
  en: {
    'nav.about': 'About', 'nav.work': 'Work', 'nav.ideas': 'Ideas', 'nav.contact': 'Contact',

    'hero.eyebrow': 'est. mmxxv / vsike.com',
    'hero.tagline': '<span class="em">velocity.</span>  style.  instinct.',
    'hero.sub': 'A digital atelier at the intersection of vision and velocity. Where design meets instinct, and ideas become momentum.',
    'hero.cta1': 'Enter the space  →', 'hero.cta2': 'View work',

    'qn.about.desc': 'The story, the why, the vision behind vsike.',
    'qn.work.desc': 'Selected projects and digital experiments.',
    'qn.ideas.desc': 'Thinking out loud. Notes from the field.',
    'qn.contact.desc': "Let's build something worth remembering.",

    'phi.label': 'Philosophy',
    'phi.quote': '“We move fast, but we never lose sight of the details that make things beautiful.”',
    'phi.p1': "vsike was born from a simple belief: that speed and elegance aren’t opposites. That you can ship with velocity and still obsess over the pixel. That instinct, refined by experience, is the sharpest tool in any maker’s kit.",
    'phi.p2': 'We live in an age of infinite noise. vsike is a signal — deliberate, considered, relentless in its pursuit of what actually matters.',
    'phi.p3': 'Every line of code, every composition, every word chosen here is the product of that obsession. Not perfection for its own sake — momentum with precision.',
    'phi.cta': 'Read the manifesto  →',
    'stat.iterations': 'Iterations', 'stat.direction': 'Direction', 'stat.forward': 'Always forward',

    'about.eyebrow': 'About vsike',
    'about.title': 'Vision.<br>Style.<br>Instinct.',
    'about.sub': 'A philosophy, a practice, and an obsession with making things that actually matter.',
    'manifesto.label': 'The Manifesto',
    'manifesto.intro': "vsike is not a studio. It’s not an agency. It’s a stance.",
    'manifesto.p1': "In a world that rewards speed over substance, vsike bets on both. True velocity isn’t just fast — it’s directed. It’s the kind of momentum that comes from knowing exactly where you’re going, and why each step matters.",
    'manifesto.p2': "Style, here, isn’t decoration. It’s clarity made visible. The discipline to remove everything that doesn’t belong, and the courage to commit fully to what does. A style is a worldview — consistent, recognizable, earned.",
    'manifesto.p3': "And instinct? That’s the hardest thing to teach and the most valuable thing to develop. The gut-level knowing that comes from years of looking, making, failing, and looking again. vsike exists to sharpen that edge — for the work, and for the maker behind it.",
    'manifesto.p4': 'We believe the best work happens at the intersection of all three: a clear vision to aim at, the style to carry it through, and the instinct to know when you’ve arrived.',
    'pillar.v': 'Vision', 'pillar.s': 'Style', 'pillar.i': 'Instinct',
    'path.label': 'The Path',
    'about.cta.text': "Ready to see what we’ve made?",
    'about.cta1': 'View work  →', 'about.cta2': 'Get in touch',

    'work.eyebrow': 'Selected Work',
    'work.title': "Things<br>we’ve built.",
    'work.sub': 'A curated collection of digital work — interfaces, systems, and experiments made with intention.',
    'work.section.label': 'Projects', 'work.section.count': '06 works',
    'work.cta1': 'Start a project  →', 'work.cta2.label': 'New inquiries open',

    'ideas.eyebrow': 'Ideas',
    'ideas.title': 'Thinking<br>out loud.',
    'ideas.sub': 'Notes on AI security, design, and the places where they collide. Covering LLM exploits, zero-days, and the craft of building things that last.',
    'ideas.section.label': 'All Posts', 'ideas.section.count': '66 entries',
    'ideas.loop.label': 'Stay in the loop',
    'ideas.loop.title': "New ideas, when they’re ready.",
    'ideas.loop.cta': 'Get notified  →',

    'contact.eyebrow': 'Contact',
    'contact.title': "Let’s make<br>something.",
    'contact.sub': "New projects, collaborations, sharp ideas — all welcome. If it’s worth building, it’s worth talking about.",
    'contact.direct': 'Direct line', 'contact.elsewhere': 'Elsewhere',
    'contact.available': 'Available for new projects — 2025',
    'contact.based': 'Based', 'contact.form.title': 'Send a message',
    'contact.form.name': 'Name', 'contact.form.email': 'Email',
    'contact.form.subject': 'Subject', 'contact.form.message': 'Message',
    'contact.form.submit': 'Send message  →', 'contact.form.sent': 'Message sent →',
    'contact.placeholder.name': 'Your name',
    'contact.placeholder.subject': "What’s this about?",
    'contact.placeholder.message': 'Tell me about your project, idea, or just say hello.',
    'contact.quote': '”The best collaborations start with someone who has a real problem and someone who genuinely wants to solve it.”',
    'contact.link.site.label': 'About this site',
    'contact.link.site': 'Stack, design decisions & colophon  →',
    'contact.link.careers.label': 'Join the team',
    'contact.link.careers': 'View open roles  →',
    'nav.site': 'This Site',
    'nav.careers': 'Careers',
    'nav.privacy': 'Privacy Policy',
    'consent.message': 'We use cookies to measure site traffic and improve your experience. See our <a href="/privacy.html">Privacy Policy</a>.',
    'consent.accept': 'Accept',
    'consent.decline': 'Decline',
    'privacy.title': 'Privacy Policy',
    'privacy.updated': 'Last updated: June 2026',
    'privacy.intro': 'vsike ("we", "us", or "our") is committed to protecting your privacy. This policy explains what data we collect, how we use it, and your rights.',
    'privacy.s1.title': 'Information We Collect',
    'privacy.s1.body': 'We collect anonymized usage data through Google Analytics 4 (page views, session duration, referral source, device type). We do not collect personally identifiable information unless you contact us directly via our contact form.',
    'privacy.s2.title': 'Cookies',
    'privacy.s2.body': 'We use first-party cookies to remember your language preference. With your consent, we also use third-party cookies from Google Analytics to understand how visitors use this site, and Google AdSense to serve relevant advertisements.',
    'privacy.s3.title': 'How We Use Your Data',
    'privacy.s3.body': 'Usage data is used solely to improve site content and performance. We do not sell, rent, or share your data with third parties except as required by the services listed above.',
    'privacy.s4.title': 'Your Rights (GDPR / CCPA)',
    'privacy.s4.body': "You have the right to access, correct, or delete data we hold about you. You may withdraw cookie consent at any time by clearing your browser's local storage. For California residents: we do not sell personal information.",
    'privacy.s5.title': 'Third-Party Services',
    'privacy.s5.body': 'This site uses Google Analytics 4 and Google AdSense. These services may set cookies and collect data according to <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google\'s Privacy Policy</a>.',
    'privacy.s6.title': 'Contact',
    'privacy.s6.body': 'Questions about this policy? Email us at <a href="mailto:help@vsike.com">help@vsike.com</a>.',
    'article.back': '← All Ideas',
    'idea.66.title': 'AI Postmortem & Runbook Automation: From 3 Hours to 20 Minutes',
    'idea.66.excerpt': 'AI can compress postmortem writing from 3 hours to 20 minutes and generate runbook first drafts from incident timelines. Here is how to automate the right parts, keep the human analysis intact, and build a postmortem corpus that makes future incidents shorter.',
    'idea.66.date': 'May 2026',
    'idea.66.cat': 'SRE',
    'idea.65.title': 'MCP Tools for SRE Observability: Giving Your Agent Eyes',
    'idea.65.excerpt': 'Model Context Protocol lets SRE agents query Elasticsearch, Prometheus, Honeycomb, and Kubernetes in natural language. Here is what the MCP tool surface looks like for a real observability stack, and what changes when the agent can see everything.',
    'idea.65.date': 'May 2026',
    'idea.65.cat': 'SRE',
    'idea.64.title': 'AI Agent On-Call: From Alert to Root Cause Without Waking Anyone Up',
    'idea.64.excerpt': 'PagerDuty and Azure SRE Agents report 75% lower MTTR in 2026. Here is how to structure an AI-assisted on-call workflow: what to automate, where to keep humans in the loop, and how to avoid the false confidence trap.',
    'idea.64.date': 'May 2026',
    'idea.64.cat': 'SRE',
    'idea.63.title': 'Calm Interfaces: Designing for Attention in the Age of AI',
    'idea.63.excerpt': 'The dominant UI trend of 2026 is not maximalism or AI-first automation. It is restraint. Calm interfaces that respect human attention, surface AI as a thoughtful copilot, and refuse to amplify noise.',
    'idea.63.date': 'May 2026',
    'idea.63.cat': 'Design',
    'idea.62.title': 'When the Interface Is the Attack Surface: Generative UI Security',
    'idea.62.excerpt': 'AI-generated interfaces can hallucinate dark patterns, render XSS payloads, and systematically violate WCAG — not through malice, but through statistical plausibility. When the UI itself is model output, the security model must treat the interface as untrusted.',
    'idea.62.date': 'May 2026',
    'idea.62.cat': 'AI Security',
    'idea.61.title': 'Agentic Memory Poisoning: The Attack That Waits',
    'idea.61.excerpt': 'Prompt injection ends when the conversation closes. Memory poisoning does not. The MINJA attack achieves 95% injection success with a payload that sits dormant until the right future query activates it — days or weeks later.',
    'idea.61.date': 'May 2026',
    'idea.61.cat': 'AI Security',
    'idea.60.title': 'Agent Identity in 2026: Five Competing Standards and No Clear Winner',
    'idea.60.excerpt': 'RSAC 2026 saw five major vendors launch incompatible agent identity frameworks in the same week. Protocol fragmentation is not just an interoperability problem — when an agent cannot verify the identity of the agent it is talking to, every delegation becomes a trust assumption.',
    'idea.60.date': 'May 2026',
    'idea.60.cat': 'AI Security',
    'idea.59.title': 'The Multi-Hop Delegation Problem: Token Chains in Multi-Agent Systems',
    'idea.59.excerpt': 'When Agent A delegates to Agent B which delegates to Agent C, who actually authorized the final action? Multi-agent delegation chains are breaking the accountability model that OAuth was designed to provide — and most frameworks don\'t enforce scope narrowing at all.',
    'idea.59.date': 'May 2026',
    'idea.59.cat': 'AI Security',
    'idea.58.title': 'When Authorization Outlives Intent: Short-Lived Credentials in Agentic AI',
    'idea.58.excerpt': '65% of agentic chatbots have never been used yet still hold live access credentials. Token lifetime is not a configuration detail — it is the primary blast-radius control for every agentic system in production. One stale credential, seven hundred breach notifications.',
    'idea.58.date': 'May 2026',
    'idea.58.cat': 'AI Security',
    'idea.57.title': 'Data Visualization as Communication',
    'idea.57.excerpt': 'A chart that requires a legend to decode is a chart that failed. The best data visualizations make their argument without explanation. Chart type as semantic choice, the data-ink ratio, annotation over legend, honest scales — and why misleading visualizations destroy trust faster than bad data does.',
    'idea.57.date': 'May 2026',
    'idea.57.cat': 'Design',
    'idea.56.title': 'Accessibility Is Not an Afterthought',
    'idea.56.excerpt': 'Designing for the edges of human capability doesn\'t produce a restricted interface — it produces a better one. The curb cut effect, POUR principles, color contrast, focus management, screen reader semantics, and why accessibility constraints force the clarity every interface should have by default.',
    'idea.56.date': 'May 2026',
    'idea.56.cat': 'Design',
    'idea.55.title': 'Loading States Are Interface Communication',
    'idea.55.excerpt': 'A spinner is not a design decision — it\'s a surrender. Every loading state is an opportunity to tell the user something true about what\'s happening. Skeleton screens vs spinners, progressive loading, optimistic UI, and why specific loading copy beats a bare animation every time.',
    'idea.55.date': 'May 2026',
    'idea.55.cat': 'Design',
    'idea.54.title': 'AI-Powered Phishing: LLMs as Social Engineering Tools at Scale',
    'idea.54.excerpt': 'Phishing used to be detectable by bad grammar and generic salutations. LLMs eliminated both signals and now enable personalized, contextually aware attacks at a volume no human attacker could produce. The spear-phishing pipeline, voice cloning for vishing, detection evasion, and why verification protocols matter more than email filters.',
    'idea.54.date': 'May 2026',
    'idea.54.cat': 'AI Security',
    'idea.53.title': 'Agentic AI Authorization: The Permission Problem in Autonomous Systems',
    'idea.53.excerpt': 'When an AI agent asks to read your files, send your email, or execute code — how does the system decide if it should? Most agentic systems grant broad access at deployment time and never revisit it. Least-privilege per task, dynamic permission requests, capability tokens, and why every permission use needs an audit trail tied to the task that justified it.',
    'idea.53.date': 'May 2026',
    'idea.53.cat': 'AI Security',
    'idea.52.title': 'LLM Denial-of-Service: Token Flooding, Sponge Examples, and Resource Exhaustion',
    'idea.52.excerpt': 'LLMs are uniquely vulnerable to resource exhaustion: the attacker pays almost nothing while the defender pays per token. Token flooding, sponge examples that maximize compute at inference time, recursive expansion attacks, and context window stuffing — plus output token limits, cost-based circuit breakers, and request queuing that actually work.',
    'idea.52.date': 'May 2026',
    'idea.52.cat': 'AI Security',
    'idea.51.title': 'AI Security Incident Response: When Your Model Gets Weaponized',
    'idea.51.excerpt': 'AI incidents are different from traditional breaches — there\'s no clear breach moment, behavioral drift is hard to detect, and "rollback" is more complex than reverting a deploy. Detection signals, containment steps, investigation framework for tracing the attack vector, and recovery procedures that close the door before you re-open the system.',
    'idea.51.date': 'May 2026',
    'idea.51.cat': 'AI Security',
    'idea.50.title': 'Hardening System Prompts: Defense-in-Depth for LLM Applications',
    'idea.50.excerpt': 'The system prompt is the first line of defense in any LLM application — and the most commonly misconfigured one. Instruction anchoring, explicit refusal directives, output constraints, canary tokens for leakage detection, and why no amount of prompt engineering substitutes for access control, model training, or architectural isolation.',
    'idea.50.date': 'May 2026',
    'idea.50.cat': 'AI Security',
    'idea.49.title': 'Zero-Trust Architecture for AI Systems: Never Trust, Always Verify',
    'idea.49.excerpt': 'Traditional perimeter security fails AI where every model, agent, and pipeline is an internal attack surface. Five zero-trust layers: cryptographic workload identity (SPIFFE/SPIRE), least-privilege tool scoping, data micro-segmentation, continuous output authorization gates, and immutable audit logging the AI system itself cannot delete.',
    'idea.49.date': 'May 2026',
    'idea.49.cat': 'AI Security',
    'idea.48.title': 'AI Governance and Compliance: Building Accountable AI Systems',
    'idea.48.excerpt': 'The EU AI Act, NIST AI RMF, and sector-specific regulations (SR 11-7, FDA SaMD) are creating concrete compliance obligations. Governance requires traceability, human oversight, continuous monitoring, incident response, and third-party model governance built in from the start — not bolted on after deployment.',
    'idea.48.date': 'May 2026',
    'idea.48.cat': 'AI Security',
    'idea.47.title': 'LLM API Security: Rate Limiting, Auth, and Prompt Leakage',
    'idea.47.excerpt': 'LLM APIs introduce attack surfaces that don\'t exist in traditional REST services: system prompt leakage, cost exhaustion attacks (one prompt can burn $50 in compute), cross-user injection through shared context windows, and session isolation failures. Why most rate-limiting implementations are wrong for AI workloads.',
    'idea.47.date': 'May 2026',
    'idea.47.cat': 'AI Security',
    'idea.46.title': 'AI Supply Chain Security: Compromised Weights and Poisoned Repos',
    'idea.46.excerpt': 'Pickle deserialization gives arbitrary code execution the moment you load a malicious model checkpoint. With 500,000+ models on HuggingFace, typosquatting, compromised maintainer accounts, and poisoned fine-tuning datasets represent a supply chain attack surface the ML community is only beginning to address.',
    'idea.46.date': 'May 2026',
    'idea.46.cat': 'AI Security',
    'idea.45.title': 'Adversarial Inputs: When AI Sees What Isn\'t There',
    'idea.45.excerpt': 'Imperceptible pixel perturbations cause confident misclassification — the fundamental geometry of adversarial attacks. Four attack categories (white-box, black-box, physical-world, universal perturbations) and three deployment scenarios: autonomous vehicle perception, biometric bypass, and content moderation evasion. Why defenses keep failing.',
    'idea.45.date': 'May 2026',
    'idea.45.cat': 'AI Security',
    'idea.44.title': 'Model Theft: Extracting Proprietary AI via API Queries',
    'idea.44.excerpt': 'With 10k–100k queries, attackers can train a local model that achieves 90%+ behavioral agreement with a commercial API — effectively stealing the training investment. Three attacker goals (behavioral clone, white-box proxy, safety bypass) and why logit-masking defenses fail against distillation-based extraction.',
    'idea.44.date': 'May 2026',
    'idea.44.cat': 'AI Security',
    'idea.43.title': 'Training Data Extraction: Stealing Private Data from Public Models',
    'idea.43.excerpt': 'Nasr et al. (2023) extracted ChatGPT training data including real email addresses and personal data using a $200 divergence attack. Memorization is a feature, not a bug — models must memorize to generalize. Four memorization factors and three extraction techniques that work against production LLMs.',
    'idea.43.date': 'May 2026',
    'idea.43.cat': 'AI Security',
    'idea.42.title': 'Multimodal Prompt Injection: Instructions Hidden in Images',
    'idea.42.excerpt': 'Text rendered in white-on-white, steganographic LSB embedding, QR codes in document corners, natural-language overlays on product photos — four vectors for hiding AI instructions inside image content. When a vision-capable agent processes your uploaded receipt and executes the attacker\'s instructions instead of summarizing expenses.',
    'idea.42.date': 'May 2026',
    'idea.42.cat': 'AI Security',
    'idea.41.title': 'Design Tokens: The Single Source of Truth for Visual Style',
    'idea.41.excerpt': 'Design tokens are the atomic units of a design system — named variables for color, spacing, typography, and motion that connect design tools to production code. The three-layer architecture, how dark mode becomes a token swap instead of a codebase audit, and naming conventions that scale.',
    'idea.41.date': 'May 2026',
    'idea.41.cat': 'Design',
    'idea.40.title': 'Form Design: The Interface Nobody Thinks About',
    'idea.40.excerpt': 'Forms are where users do the work. Validation timing, label vs. placeholder, the questions you shouldn\'t ask, and why forms are conversations — not questionnaires. Every unnecessary field is a question that insults the user\'s time.',
    'idea.40.date': 'May 2026',
    'idea.40.cat': 'Design',
    'idea.39.title': 'Motion Design Principles: Animation That Earns Its Place',
    'idea.39.excerpt': 'Motion in interface design has one job: reduce cognitive load by making state changes perceptible. Duration tables, the four principles of purposeful motion, what to avoid (bounce on controls, animating everything), and how to build a motion system that creates coherent product feel.',
    'idea.39.date': 'May 2026',
    'idea.39.cat': 'Design',
    'idea.38.title': 'AI Red Teaming Methodology: Breaking Models on Purpose',
    'idea.38.excerpt': 'Red teaming AI systems requires a different methodology than traditional software. A four-phase process — threat model, attack technique families (jailbreaking, prompt extraction, indirect injection, capability elicitation), systematic coverage, and reporting — plus why attack success rate matters more than existence.',
    'idea.38.date': 'May 2026',
    'idea.38.cat': 'AI Security',
    'idea.37.title': 'Agent Sandboxing: Containing AI in Production',
    'idea.37.excerpt': 'Process isolation doesn\'t contain what an AI agent decides to do. The primary escape vector is prompt injection through tool outputs — a five-layer containment architecture covering capability minimization, output validation, data flow control, human confirmation gates, and tool output sanitization.',
    'idea.37.date': 'May 2026',
    'idea.37.cat': 'AI Security',
    'idea.36.title': 'LLM Fine-tuning Security: Backdoors You Train In',
    'idea.36.excerpt': 'Fine-tuning on custom data can override safety alignment trained into the base model. How backdoor attacks embed hidden triggers at 0.1% contamination rates, the four attack surfaces (data poisoning, alignment erosion, instruction injection, membership inference), and mitigations that actually transfer to the fine-tuned version.',
    'idea.36.date': 'May 2026',
    'idea.36.cat': 'AI Security',
    'idea.35.title': 'AI-Assisted Social Engineering: Deepfakes, Voice Cloning, and Spear Phishing at Scale',
    'idea.35.excerpt': 'AI has collapsed the cost curve of impersonation attacks. Spear phishing at $0.01 per target, voice cloning from 3 seconds of audio, real-time deepfake video in browser tabs. The Hong Kong CFO fraud case, why detection arms races favor attackers, and what actually works for defense.',
    'idea.35.date': 'May 2026',
    'idea.35.cat': 'AI Security',
    'idea.34.title': 'LLM Hallucination as a Security Vector',
    'idea.34.excerpt': 'Hallucinated package names get installed. Hallucinated URLs get visited. Slopsquatting — publishing packages at names LLMs consistently hallucinate — lets attackers weaponize model errors at scale. Why confidence amplifies the risk, and how to verify before you install.',
    'idea.34.date': 'May 2026',
    'idea.34.cat': 'AI Security',
    'idea.33.title': 'Error States: Designing for Failure',
    'idea.33.excerpt': 'Most design systems are designed for success. Error states are afterthoughts — vague, blame-shifting, and unhelpful. The anatomy of a bad error message, what makes one good, and why empty states are the most underused onboarding opportunity in any product.',
    'idea.33.date': 'May 2026',
    'idea.33.cat': 'Design',
    'idea.32.title': 'Color Systems: Beyond the Palette',
    'idea.32.excerpt': 'A palette is a collection of colors. A color system is a set of rules for how they relate and where they\'re used. The three-layer architecture (primitive, semantic, component), why dark mode is a semantic problem, and why the neutral scale is where the real design work happens.',
    'idea.32.date': 'May 2026',
    'idea.32.cat': 'Design',
    'idea.31.title': 'Typography Hierarchy: How Visual Weight Guides the Eye',
    'idea.31.excerpt': 'Hierarchy is the typographer\'s grammar. How size, weight, spacing, and color combine to create a reading order the eye follows without thinking — and the squint test that tells you whether your hierarchy is structural or just decorative.',
    'idea.31.date': 'May 2026',
    'idea.31.cat': 'Design',
    'idea.30.title': 'Memory Poisoning in AI Agents',
    'idea.30.excerpt': 'AI agents with persistent memory are uniquely vulnerable to a slow, stealthy attack: adversarial content injected into vector stores that biases agent behavior over time. Why it\'s nearly undetectable, how vector databases become the primary target, and what memory integrity design actually requires.',
    'idea.30.date': 'May 2026',
    'idea.30.cat': 'AI Security',
    'idea.29.title': 'Browser-Use & Computer-Use: The New AI Attack Surface',
    'idea.29.excerpt': 'When AI agents can click, type, and navigate browsers autonomously, every website becomes a potential attack vector. Hidden page instructions, ARIA label injection, financial fraud via mid-task manipulation — the threat model is fundamentally different from chat-based AI.',
    'idea.29.date': 'May 2026',
    'idea.29.cat': 'AI Security',
    'idea.28.title': 'System Prompt Extraction: How Attackers Steal Your LLM Configuration',
    'idea.28.excerpt': 'System prompts are not secrets. Five reliable extraction techniques — from direct instruction to differential probing to token smuggling via tool calls — and why designing your product assuming the prompt is public is the only safe posture.',
    'idea.28.date': 'May 2026',
    'idea.28.cat': 'AI Security',
    'idea.27.title': 'OWASP LLM Top 10: A Practical Field Guide',
    'idea.27.excerpt': 'The OWASP Top 10 for LLM Applications from specification to practice. Real attack patterns and mitigations for all ten categories — from Prompt Injection and Insecure Output Handling to Excessive Agency and Model Theft — with a prioritization framework for shipping teams.',
    'idea.27.date': 'May 2026',
    'idea.27.cat': 'AI Security',
    'idea.26.title': 'AI Worms: When Agents Infect Each Other',
    'idea.26.excerpt': 'Self-replicating prompts that spread through multi-agent systems without any user interaction. Morris II demonstrated this in 2024. How propagation works, why standard defenses fail, and the mitigations that actually help — privilege separation, human confirmation gates, and memory integrity checks.',
    'idea.26.date': 'May 2026',
    'idea.26.cat': 'AI Security',
    'idea.25.title': 'White Space Is Not Empty',
    'idea.25.excerpt': 'The blank areas in a design aren\'t the absence of design — they\'re the most active part of it. A case for negative space as the primary tool of visual hierarchy, grouping, emphasis, and rhythm. Plus the spacing system problem that causes most visual inconsistency in production.',
    'idea.25.date': 'May 2026',
    'idea.25.cat': 'Design',
    'idea.24.title': 'OAuth 2.0\'s Agent Problem: When AI Tokens Live Forever',
    'idea.24.excerpt': 'AI agents inherit OAuth tokens that outlive their tasks, accumulate scopes across sessions, and become high-value targets when stored in MCP config files. The authorization model wasn\'t designed for autonomous agents — here\'s what secure agent authorization actually requires.',
    'idea.24.date': 'May 2026',
    'idea.24.cat': 'Web Security',
    'idea.23.title': 'Indirect Prompt Injection via Tool Outputs',
    'idea.23.excerpt': 'The injection variant that bypasses every system-prompt defense: adversarial instructions embedded in MCP tool responses, database records, and retrieved web content. Why standard defenses fail, and how the MCP tool layer amplifies the blast radius.',
    'idea.23.date': 'May 2026',
    'idea.23.cat': 'AI Security',
    'idea.22.title': 'MCP Complete Guide: What It Is, How to Build It, How to Use It',
    'idea.22.excerpt': 'Model Context Protocol from first principles: the Host/Client/Server architecture, building MCP servers in TypeScript and Python with real code examples, configuring Claude Desktop, and understanding when MCP is the right tool versus other approaches.',
    'idea.22.date': 'May 2026',
    'idea.22.cat': 'AI Development',
    'idea.21.title': 'AI Skills vs MCP: Workflow Layer vs Tool Layer',
    'idea.21.excerpt': 'Skills and MCP both extend AI agents, but at completely different layers. Skills define what the agent does (CLAUDE.md slash commands, reusable workflows); MCP defines what the agent can reach (external tools, APIs, databases). How to create both, and how they compose.',
    'idea.21.date': 'May 2026',
    'idea.21.cat': 'AI Development',
    'idea.20.title': '2026 Linux Kernel LPE Trilogy: Copy Fail, Dirty Frag & Fragnesia',
    'idea.20.excerpt': 'Three critical local privilege escalation vulnerabilities — CVE-2026-31431, CVE-2026-43284/43500, CVE-2026-46300 — all actively exploited in spring 2026. Breakdown, detection, and exact patch commands for Ubuntu, RHEL, and SUSE.',
    'idea.20.date': 'May 2026',
    'idea.20.cat': 'Zero-Day',
    'idea.19.title': 'NGINX Rift: 18-Year-Old Rewrite Flaw Enables RCE (CVE-2026-42945)',
    'idea.19.excerpt': 'A heap buffer overflow in nginx\'s rewrite module — dormant since 2008, CVSS 9.2, no auth required — was disclosed April 2026 and immediately exploited. How to detect vulnerable configs and patch or mitigate now.',
    'idea.19.date': 'May 2026',
    'idea.19.cat': 'Zero-Day',
    'idea.18.title': 'Vibe Coding\'s Hidden Security Bill',
    'idea.18.excerpt': 'Developers using AI coding assistants are shipping features faster than ever. They\'re also shipping vulnerabilities faster than ever. The security debt of vibe coding is real, accumulating, and largely invisible until it isn\'t.',
    'idea.18.date': 'May 2025',
    'idea.18.cat': 'AI Security',
    'idea.17.title': 'MCP: The New Attack Surface Nobody Saw Coming',
    'idea.17.excerpt': 'Anthropic\'s Model Context Protocol gives AI agents persistent access to tools and data sources. It also gives attackers a new vector that most security teams haven\'t modeled yet — and the window to get ahead of it is closing.',
    'idea.17.date': 'May 2025',
    'idea.17.cat': 'AI Security',
    'idea.16.title': 'The Jailbreak Arms Race: Why AI Safety Keeps Falling Behind',
    'idea.16.excerpt': 'Every safety measure deployed in a large language model has been bypassed. Not some — every one. On why the jailbreak problem is structurally different from other security problems, and what that means for AI deployment.',
    'idea.16.date': 'Apr 2025',
    'idea.16.cat': 'AI Safety',
    'idea.15.title': 'DeepSeek and the Open-Source LLM Security Question',
    'idea.15.excerpt': 'DeepSeek\'s emergence forced a real conversation the AI industry had been avoiding. The model capability gap is closing. The governance gap is not. A framework for thinking about open-weight model risk.',
    'idea.15.date': 'Feb 2025',
    'idea.15.cat': 'AI Security',
    'idea.14.title': 'AI Finds 0-Day in Linux Kernel Before Any Human Did',
    'idea.14.excerpt': 'Google\'s Project Big Sleep agent autonomously discovered a memory-corruption vulnerability in the Linux kernel\'s io_uring subsystem — patched before public disclosure. The era of AI-first vulnerability research is here.',
    'idea.14.date': 'May 2025',
    'idea.14.cat': 'AI Security',
    'idea.13.title': 'Prompt Injection: The Vulnerability AI Can\'t Patch Itself',
    'idea.13.excerpt': 'Unlike buffer overflows or SQL injection, prompt injection attacks are semantic — they exploit the model\'s instruction-following nature. Understanding why this class of vulnerability is structurally different from everything that came before it.',
    'idea.13.date': 'May 2025',
    'idea.13.cat': 'LLM Security',
    'idea.12.title': 'RAG Poisoning: When Your AI Knowledge Base Becomes an Attack Vector',
    'idea.12.excerpt': 'Retrieval-Augmented Generation systems trust their data sources implicitly. Injecting adversarial content into a vector database can hijack every query that retrieves it. A walkthrough of the attack surface.',
    'idea.12.date': 'Apr 2025',
    'idea.12.cat': 'LLM Security',
    'idea.11.title': 'Sleeper Agents in LLMs: The Attack That Survives Fine-Tuning',
    'idea.11.excerpt': 'Anthropic\'s 2024 research showed that LLMs can be trained to behave normally until a specific trigger condition is met — and that standard RLHF safety training fails to remove the behavior. What this means for any organization deploying third-party models.',
    'idea.11.date': 'Apr 2025',
    'idea.11.cat': 'AI Safety',
    'idea.10.title': 'Malicious Models on Hugging Face: The New Supply Chain Attack',
    'idea.10.excerpt': 'Researchers discovered over 100 models on Hugging Face Hub containing serialized payloads that execute arbitrary code on load via pickle deserialization. The ML supply chain has the same vulnerabilities as npm — and less scrutiny.',
    'idea.10.date': 'Mar 2025',
    'idea.10.cat': 'Supply Chain',
    'idea.9.title': 'CVE-2024-6387: How a 0-Day in OpenSSH Went Undetected for 18 Years',
    'idea.9.excerpt': 'regreSSHion was a signal flare. A race-condition vulnerability dormant since 2006, rediscovered by Qualys\'s AI-assisted static analysis pipeline. On how AI-powered code auditing is surfacing bugs that escaped a generation of manual review.',
    'idea.9.date': 'Feb 2025',
    'idea.9.cat': 'Zero-Day',
    'idea.8.title': 'AI-Discovered Critical Vulnerabilities in 2025: A Running Tally',
    'idea.8.excerpt': 'From Google\'s Big Sleep SQLite buffer overflow to Microsoft\'s Security Copilot flagging misconfigurations in Azure — a curated log of vulnerabilities where AI either found the bug, accelerated the patch, or changed the disclosure timeline.',
    'idea.8.date': 'Jan 2025',
    'idea.8.cat': 'AI Security',
    'idea.7.title': 'The Case Against Consistent Design',
    'idea.7.excerpt': 'Why the obsession with pixel-perfect consistency might be the thing that\'s making your product feel lifeless — and what to reach for instead.',
    'idea.7.date': 'May 2025',
    'idea.7.cat': 'Design',
    'idea.6.title': 'Monospace as Aesthetic Statement',
    'idea.6.excerpt': 'There\'s a reason the most interesting corners of the web keep reaching for fixed-width fonts. It\'s not nostalgia — it\'s a precision play.',
    'idea.6.date': 'Apr 2025',
    'idea.6.cat': 'Typography',
    'idea.5.title': 'Speed Is a Design Choice',
    'idea.5.excerpt': 'Performance and aesthetics are the same conversation. A 3-second load time isn\'t a technical problem — it\'s a trust problem, a brand problem, a relationship problem.',
    'idea.5.date': 'Mar 2025',
    'idea.5.cat': 'Performance',
    'idea.4.title': 'The Grain Always Comes Back',
    'idea.4.excerpt': 'On the resurgence of texture in digital interfaces, and why generations of designers keep rediscovering that the most modern surfaces are never perfectly smooth.',
    'idea.4.date': 'Feb 2025',
    'idea.4.cat': 'Texture',
    'idea.3.title': 'What Dark Mode Actually Means',
    'idea.3.excerpt': 'Dark mode isn\'t an accessibility feature or a user preference toggle. For some of us, it\'s the only honest way to work — a disposition, not a setting.',
    'idea.3.date': 'Jan 2025',
    'idea.3.cat': 'Philosophy',
    'idea.2.title': 'Static Sites and the Long Game',
    'idea.2.excerpt': 'Every framework promises the future. HTML has already survived three decades. There\'s something to be said for betting on the thing that doesn\'t need updating.',
    'idea.2.date': 'Dec 2024',
    'idea.2.cat': 'Web',
    'idea.1.title': 'Why I Keep Coming Back to Georgia',
    'idea.1.excerpt': 'Screen-native, battle-tested, and more expressive than anything that came after it. The most underrated typeface in the history of digital design is already on your device.',
    'idea.1.date': 'Nov 2024',
    'idea.1.cat': 'Typography',
  },

  zh: {
    'nav.about': '关于', 'nav.work': '作品', 'nav.ideas': '想法', 'nav.contact': '联系',

    'hero.eyebrow': '创立 mmxxv / vsike.com',
    'hero.tagline': '<span class="em">速度。</span>  风格。  直觉。',
    'hero.sub': '一间聚焦于视觉与速度交汇处的数字工作室。设计与直觉在此相遇，想法化为前进的动力。',
    'hero.cta1': '进入空间  →', 'hero.cta2': '查看作品',

    'qn.about.desc': '关于 vsike 的故事、初心与愿景。',
    'qn.work.desc': '精选项目与数字实验。',
    'qn.ideas.desc': '大声思考，来自实践的笔记。',
    'qn.contact.desc': '让我们共同创造值得被记住的东西。',

    'phi.label': '理念',
    'phi.quote': '「我们快速前行，但从不忽视那些让事物变得美好的细节。」',
    'phi.p1': 'vsike 诞生于一个简单的信念：速度与优雅并不对立。你可以快速交付，同时仍然对每一个像素精益求精。经验磨砺的直觉，是每一位创造者工具箱中最锋利的武器。',
    'phi.p2': '我们生活在一个充满无尽噪音的时代。vsike 是一个信号——深思熟虑，有的放矢，不懈追求真正重要的事物。',
    'phi.p3': '这里的每一行代码、每一种构图、每一个选词，都是这种执念的产物。不是为了完美而完美——而是带有精准的动力。',
    'phi.cta': '阅读宣言  →',
    'stat.iterations': '迭代', 'stat.direction': '方向', 'stat.forward': '始终向前',

    'about.eyebrow': '关于 vsike',
    'about.title': '愿景。<br>风格。<br>直觉。',
    'about.sub': '一种哲学，一种实践，一种对真正有价值的事物的执着追求。',
    'manifesto.label': '宣言',
    'manifesto.intro': 'vsike 不是一个工作室，不是一家机构。它是一种立场。',
    'manifesto.p1': '在一个奖励速度而非深度的世界里，vsike 两者兼顾。真正的速度不只是快——它是有方向的。它是那种来自清晰知道自己去向何处、以及为何每一步都重要的动力。',
    'manifesto.p2': '风格，在这里，不是装饰。它是被具象化的清晰。是去除一切不属于这里的事物的纪律，以及全力投入于真正所需之物的勇气。风格是一种世界观——一致的、可辨识的、被赋予的。',
    'manifesto.p3': '那直觉呢？那是最难教授却最值得培养的东西。多年观察、创作、失败、再观察所积累的那种本能。vsike 存在的意义，就是磨砺这把利刃——为了作品，也为了背后的创造者。',
    'manifesto.p4': '我们相信，最好的作品发生在三者的交汇处：一个清晰的愿景作为目标，一种风格贯穿始终，以及一种当你到达时便能知晓的直觉。',
    'pillar.v': '愿景', 'pillar.s': '风格', 'pillar.i': '直觉',
    'path.label': '我们的历程',
    'about.cta.text': '准备好看看我们做了什么？',
    'about.cta1': '查看作品  →', 'about.cta2': '联系我们',

    'work.eyebrow': '精选作品',
    'work.title': '我们构建<br>的作品。',
    'work.sub': '一批精心策划的数字作品——有意为之的界面、系统与实验。',
    'work.section.label': '项目', 'work.section.count': '06 件',
    'work.cta1': '开启项目  →', 'work.cta2.label': '现开放新项目咨询',

    'ideas.eyebrow': '想法',
    'ideas.title': '大声<br>思考。',
    'ideas.sub': '关于 AI 安全、设计以及两者交汇之处的笔记。涵盖 LLM 漏洞、零日攻击与经久耐用的构建之道。',
    'ideas.section.label': '全部文章', 'ideas.section.count': '66 篇',
    'ideas.loop.label': '保持关注',
    'ideas.loop.title': '新想法，准备好就发布。',
    'ideas.loop.cta': '订阅通知  →',

    'contact.eyebrow': '联系',
    'contact.title': '来做点<br>什么吧。',
    'contact.sub': '新项目、合作机会、犀利想法——一切皆欢迎。值得构建的，就值得谈论。',
    'contact.direct': '直接联系', 'contact.elsewhere': '社交媒体',
    'contact.available': '现接受新项目 — 2025',
    'contact.based': '位置', 'contact.form.title': '发送消息',
    'contact.form.name': '姓名', 'contact.form.email': '邮箱',
    'contact.form.subject': '主题', 'contact.form.message': '消息',
    'contact.form.submit': '发送消息  →', 'contact.form.sent': '消息已发送 →',
    'contact.placeholder.name': '您的姓名',
    'contact.placeholder.subject': '主题是什么？',
    'contact.placeholder.message': '请告诉我您的项目、想法，或只是打个招呼。',
    'contact.quote': '「最好的合作，始于真正有问题的人，遇见真正想解决问题的人。」',
    'contact.link.site.label': '关于本站',
    'contact.link.site': '技术栈、设计决策与版权页  →',
    'contact.link.careers.label': '加入团队',
    'contact.link.careers': '查看开放职位  →',
    'nav.site': '本站',
    'nav.careers': '招聘',
    'nav.privacy': '隐私政策',
    'consent.message': '我们使用 Cookie 统计访问量并改善体验。详见 <a href="/privacy.html">隐私政策</a>。',
    'consent.accept': '接受',
    'consent.decline': '拒绝',
    'privacy.title': '隐私政策',
    'privacy.updated': '最后更新：2026年6月',
    'privacy.intro': 'vsike（以下简称"我们"）致力于保护您的隐私。本政策说明我们收集的数据、使用方式及您的权利。',
    'privacy.s1.title': '信息收集',
    'privacy.s1.body': '我们通过 Google Analytics 4 收集匿名使用数据（页面浏览量、会话时长、来源、设备类型）。除非您通过联系表单主动联系我们，否则我们不收集个人身份信息。',
    'privacy.s2.title': 'Cookie',
    'privacy.s2.body': '我们使用第一方 Cookie 记住您的语言偏好。在您同意后，我们还使用 Google Analytics 的第三方 Cookie 了解访客行为，以及 Google AdSense Cookie 投放相关广告。',
    'privacy.s3.title': '数据使用',
    'privacy.s3.body': '使用数据仅用于改善网站内容和性能。除上述服务外，我们不向第三方出售、出租或共享您的数据。',
    'privacy.s4.title': '您的权利（GDPR / CCPA）',
    'privacy.s4.body': '您有权访问、更正或删除我们持有的您的数据。您可以随时通过清除浏览器本地存储来撤回 Cookie 同意。加州居民：我们不出售个人信息。',
    'privacy.s5.title': '第三方服务',
    'privacy.s5.body': '本站使用 Google Analytics 4 和 Google AdSense。这些服务可能设置 Cookie 并按 <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google 隐私政策</a> 收集数据。',
    'privacy.s6.title': '联系方式',
    'privacy.s6.body': '如对本政策有疑问，请发送邮件至 <a href="mailto:help@vsike.com">help@vsike.com</a>。',
    'article.back': '← 全部想法',
    'idea.66.title': 'AI 故障复盘与 Runbook 自动化：从 3 小时到 20 分钟',
    'idea.66.excerpt': 'AI 可以将故障复盘写作从 3 小时压缩到 20 分钟，并从事故时间线生成 Runbook 初稿。本文介绍如何自动化正确的部分，保留人工分析，并构建让未来事故更短的复盘语料库。',
    'idea.66.date': '2026年5月',
    'idea.66.cat': 'SRE',
    'idea.65.title': 'MCP 工具与 SRE 可观测性：为 Agent 装上眼睛',
    'idea.65.excerpt': 'Model Context Protocol 让 SRE Agent 能用自然语言查询 Elasticsearch、Prometheus、Honeycomb 和 Kubernetes。本文介绍真实可观测性栈的 MCP 工具面，以及当 Agent 能看到一切时会发生什么变化。',
    'idea.65.date': '2026年5月',
    'idea.65.cat': 'SRE',
    'idea.64.title': 'AI Agent 值班：从告警到根因',
    'idea.64.excerpt': 'PagerDuty 和 Azure SRE Agent 在 2026 年实现 MTTR 降低 75%。本文介绍如何构建 AI 辅助值班工作流：哪些环节自动化、哪些保留人工、如何避免虚假信心陷阱。',
    'idea.64.date': '2026年5月',
    'idea.64.cat': 'SRE',
    'idea.63.title': '平静界面：为注意力而设计',
    'idea.63.excerpt': '2026 年 UI 的主导趋势不是极繁主义或 AI 优先的自动化，而是克制。平静界面尊重人类注意力，将 AI 作为体贴的副驾驶展示，拒绝放大噪音。',
    'idea.63.date': '2026年5月',
    'idea.63.cat': '设计',
    'idea.62.title': '当界面成为攻击面：生成式 UI 安全',
    'idea.62.excerpt': 'AI 生成的界面可以幻觉出暗黑模式、渲染 XSS 载荷、系统性违反 WCAG——不是出于恶意，而是统计上的合理性。当 UI 本身是模型输出时，安全模型必须将界面视为不可信输出。',
    'idea.62.date': '2026年5月',
    'idea.62.cat': 'AI安全',
    'idea.61.title': 'AI 代理记忆投毒：潜伏的攻击',
    'idea.61.excerpt': '提示词注入在对话结束时失效，记忆投毒不会。MINJA 攻击实现 95% 注入成功率，载荷在记忆中潜伏，等待数天或数周后的触发查询激活。',
    'idea.61.date': '2026年5月',
    'idea.61.cat': 'AI安全',
    'idea.60.title': '2026年的智能体身份：五个标准，没有赢家',
    'idea.60.excerpt': 'RSAC 2026 见证了五大主要供应商在同一周内推出不兼容的智能体身份框架。协议碎片化不仅仅是互操作性的头痛——当智能体无法验证与之通信的智能体身份时，每一次委托都变成了信任假设。',
    'idea.60.date': '2026年5月',
    'idea.60.cat': 'AI安全',
    'idea.59.title': '多跳委托问题：多智能体系统中的令牌链',
    'idea.59.excerpt': '当智能体 A 委托给智能体 B，而 B 又委托给智能体 C 时，最终操作究竟是谁授权的？多智能体委托链正在破坏 OAuth 旨在提供的问责模型。',
    'idea.59.date': '2026年5月',
    'idea.59.cat': 'AI安全',
    'idea.58.title': '当授权比意图活得更久',
    'idea.58.excerpt': '65% 的智能体聊天机器人从未被使用过，却仍持有有效的访问凭证。令牌有效期不是配置细节——它是每个生产中智能体系统的首要爆炸半径控制。',
    'idea.58.date': '2026年5月',
    'idea.58.cat': 'AI安全',
    'idea.57.title': '数据可视化即是沟通',
    'idea.57.excerpt': '需要图例才能解读的图表就是失败的图表。最好的数据可视化无需解释就能表达其论点——数据自己说话，设计退居幕后。',
    'idea.57.date': '2026年5月',
    'idea.57.cat': '设计',
    'idea.56.title': '无障碍不是事后考虑',
    'idea.56.excerpt': '为人类能力的边界进行设计不会产生受限的界面——它会产生更好的界面。每一个迫使你更清晰、更简单、更明确的无障碍约束都会改善每个人的体验。',
    'idea.56.date': '2026年5月',
    'idea.56.cat': '设计',
    'idea.55.title': '加载状态是界面通信',
    'idea.55.excerpt': '旋转图标不是设计决策——它是一种投降。每个加载状态都是告诉用户正在发生什么的机会。大多数界面浪费了它。',
    'idea.55.date': '2026年5月',
    'idea.55.cat': '设计',
    'idea.54.title': 'AI 驱动的钓鱼攻击：LLM 作为规模化社会工程工具',
    'idea.54.excerpt': '钓鱼攻击曾经可以通过糟糕的语法和通用的称呼来识别。LLM 消除了这两个信号——现在使个性化、情境感知的社会工程攻击得以规模化，这是任何人工都无法手动产生的。',
    'idea.54.date': '2026年5月',
    'idea.54.cat': 'AI安全',
    'idea.53.title': 'AI 智能体授权：自主系统中的权限问题',
    'idea.53.excerpt': '当 AI 智能体要求读取你的文件、发送你的邮件或执行代码时——系统如何决定是否应该允许？大多数智能体系统在这方面犯了容易被利用且难以审计的错误。',
    'idea.53.date': '2026年5月',
    'idea.53.cat': 'AI安全',
    'idea.52.title': 'LLM 拒绝服务攻击：令牌泛洪、海绵样本与资源耗尽',
    'idea.52.excerpt': 'LLM 对资源耗尽攻击具有独特的脆弱性。与传统 DoS 不同，LLM DoS 可以用一个精心设计的提示触发——攻击者几乎什么都不花，而防御者按令牌付费。',
    'idea.52.date': '2026年5月',
    'idea.52.cat': 'AI安全',
    'idea.51.title': 'AI 安全事件响应：当你的模型被武器化',
    'idea.51.excerpt': '检测被入侵的 AI 系统、控制损害范围，并在不重蹈覆辙的情况下恢复——这是为在生产环境中运营 AI 的团队准备的实用手册。',
    'idea.51.date': '2026年5月',
    'idea.51.cat': 'AI安全',
    'idea.50.title': '系统提示加固：LLM 应用的纵深防御',
    'idea.50.excerpt': '系统提示是 LLM 应用中的第一道防线——也是最常被错误配置的一道。以下是如何针对注入、提取和操控进行加固。',
    'idea.50.date': '2026年5月',
    'idea.50.cat': 'AI安全',
    'idea.49.title': 'AI系统的零信任架构：永不信任，始终验证',
    'idea.49.excerpt': '传统边界安全假设内部一切都是安全的。AI系统在每一层都打破了这个假设。',
    'idea.49.date': '2026年5月',
    'idea.49.cat': 'AI安全',
    'idea.48.title': 'AI 治理与合规：构建可问责的 AI 系统',
    'idea.48.excerpt': '欧盟 AI 法案、NIST AI 风险管理框架以及新兴的行业特定法规正在为部署 AI 的组织创造具体的合规义务。治理不仅仅是文档工作——它需要从一开始就构建到 AI 系统中的可追溯性、事件响应和持续监控，而非在部署后再进行改造。',
    'idea.48.date': '2026年5月',
    'idea.48.cat': 'AI安全',
    'idea.47.title': 'LLM API 安全：速率限制、认证与提示词泄露',
    'idea.47.excerpt': '通过 API 暴露 LLM 引入了与传统 Web API 不同的安全问题。系统提示词泄露、成本耗尽攻击以及基于 Token 的速率限制挑战都需要标准 API 安全无法覆盖的专门方法。',
    'idea.47.date': '2026年5月',
    'idea.47.cat': 'AI安全',
    'idea.46.title': 'AI 供应链安全：被入侵的模型权重与被污染的仓库',
    'idea.46.excerpt': 'AI 开发供应链——来自 HuggingFace 的模型权重、来自公开仓库的数据集、来自 GitHub 的微调脚本——与任何软件依赖链一样容易被攻击。恶意权重、被污染的数据集和模型名称仿冒在模型加载的瞬间执行代码，绕过应用层的每一道安全防线。',
    'idea.46.date': '2026年5月',
    'idea.46.cat': 'AI安全',
    'idea.45.title': '对抗样本：当 AI 看到不存在的东西',
    'idea.45.excerpt': '对抗样本是精心构造的输入，能以高置信度导致 AI 模型误分类——揭示了神经网络泛化方式中的根本脆弱性。带有贴纸的停车标志变成了限速标志。带有不可感知像素噪声的熊猫变成了长臂猿。',
    'idea.45.date': '2026年5月',
    'idea.45.cat': 'AI安全',
    'idea.44.title': '模型窃取：通过 API 查询提取专有 AI',
    'idea.44.excerpt': '有足够动机的攻击者可以仅通过系统性 API 查询就重建专有模型的行为——无需访问权重。模型提取攻击将你的推理端点变成竞争对手的训练数据来源，使其能够不付开发成本而获得你的模型能力。',
    'idea.44.date': '2026年5月',
    'idea.44.cat': 'AI安全',
    'idea.43.title': '训练数据提取：从公开模型中窃取私密数据',
    'idea.43.excerpt': '大型语言模型会记忆训练数据——而这些被记忆的内容可以通过精心构造的查询提取出来。个人身份信息、受版权保护的文本、专有代码和有效的 API 密钥都已从生产环境 LLM 中被提取。知道你数据的模型对每个拥有 API 密钥的人都是可访问的。',
    'idea.43.date': '2026年5月',
    'idea.43.cat': 'AI安全',
    'idea.42.title': '多模态提示注入：藏在图像中的指令',
    'idea.42.excerpt': '当视觉语言模型处理图像时，这些图像可以携带人类不可见的对抗性指令。收据照片、文件扫描件、二维码——所有这些都可以嵌入文本，以任何人工审查员都不会注意到的方式重定向模型行为。',
    'idea.42.date': '2026年5月',
    'idea.42.cat': 'AI安全',
    'idea.41.title': 'Design Tokens：视觉风格的唯一真实来源',
    'idea.41.excerpt': 'Design Tokens 是设计系统的原子单元——为颜色、间距、排版和动效命名的变量，将设计工具与生产代码连接起来。没有它们，每个团队说的是同一种视觉语言的不同方言，一致性在每个迭代中逐渐侵蚀。',
    'idea.41.date': '2026年5月',
    'idea.41.cat': '设计',
    'idea.40.title': '表单设计：没人认真对待的界面',
    'idea.40.excerpt': '表单是用户完成工作的地方。他们在这里输入地址、配置设置、提交付款、创建账户。表单质量决定用户是完成任务还是放弃——而表单设计相对于其对转化率、支持量和用户信任的巨大影响来说，长期投入不足。',
    'idea.40.date': '2026年5月',
    'idea.40.cat': '设计',
    'idea.39.title': '动效设计原则：值得存在的动画',
    'idea.39.excerpt': '界面设计中的动效只有一项职责：通过使状态变化可感知来降低认知负担。吸引用户注意自身而非它所代表的过渡的动画，是穿着"愉悦"外衣的噪音——它们积累起来让界面用起来令人疲倦。',
    'idea.39.date': '2026年5月',
    'idea.39.cat': '设计',
    'idea.38.title': 'AI 红队测试方法论：有意破坏模型',
    'idea.38.excerpt': 'AI 系统的红队测试需要与传统软件不同的方法论。提示级攻击、语义利用和能力诱导不能映射到已知的 CVE——它们需要系统地探索模型的决策边界，而且结果会随模型版本更新而失效。',
    'idea.38.date': '2026年5月',
    'idea.38.cat': 'AI安全',
    'idea.37.title': 'Agent 沙箱：在生产环境中约束 AI',
    'idea.37.excerpt': '具有工具访问权限的 AI 智能体需要远超传统进程隔离的约束策略。攻击面包括通过工具输出的提示注入、跨智能体链的能力升级，以及通过看似无害的 API 调用进行的数据泄露。',
    'idea.37.date': '2026年5月',
    'idea.37.cat': 'AI安全',
    'idea.36.title': 'LLM 微调安全：你训练进去的后门',
    'idea.36.excerpt': '微调使基础模型适应你的领域——也可能将原始安全训练旨在防止的行为偷偷带入。后门触发器、破坏对齐的样本和投毒数据集都可以通过微调流程进入，直到触发器在生产中触发时才会现形。',
    'idea.36.date': '2026年5月',
    'idea.36.cat': 'AI安全',
    'idea.35.title': 'AI 辅助的社会工程学：深度伪造、语音克隆与规模化鱼叉式网络钓鱼',
    'idea.35.excerpt': 'AI 已大幅降低个性化欺骗的成本。语音克隆只需三秒音频，费用仅为几分钱。实时深度伪造视频在消费级硬件上运行。企业规模的鱼叉式网络钓鱼在技术上已轻而易举。人类的攻击面从未像今天这样大。',
    'idea.35.date': '2026年5月',
    'idea.35.cat': 'AI安全',
    'idea.34.title': 'LLM 幻觉作为安全攻击向量',
    'idea.34.excerpt': '幻觉出来的包名被安装了。幻觉出来的 URL 被访问了。幻觉出来的代码被部署到了生产环境。当 AI 自信地捏造内容时，下游的损害是真实的——而且对于已学会预测模型会幻觉什么的攻击者来说，越来越可武器化。',
    'idea.34.date': '2026年5月',
    'idea.34.cat': 'AI安全',
    'idea.33.title': '错误状态：为失败而设计',
    'idea.33.excerpt': '大多数设计系统为成功而设计。错误状态是事后想到的——模糊、推卸责任、毫无帮助。令人沮丧的产品和赢得信任的产品之间的差距，往往恰好在这里。',
    'idea.33.date': '2026年5月',
    'idea.33.cat': '设计',
    'idea.32.title': '颜色系统：超越调色板',
    'idea.32.excerpt': '调色板是颜色的集合。颜色系统是关于它们如何关联以及在何处使用的规则集。大多数产品有调色板，很少有系统。这是区别所在——以及为何在规模上重要。',
    'idea.32.date': '2026年5月',
    'idea.32.cat': '设计',
    'idea.31.title': '排版层级：视觉权重如何引导眼睛',
    'idea.31.excerpt': '层级是排版师的语法。没有它，页面是一片喧嚣。有了它，眼睛知道该去哪里，以什么顺序——读者完全无需思考。',
    'idea.31.date': '2026年5月',
    'idea.31.cat': '设计',
    'idea.30.title': 'AI 智能体中的记忆投毒攻击',
    'idea.30.excerpt': '拥有持久记忆的 AI 智能体功能强大，但也极易遭受记忆投毒——一种缓慢、隐蔽的攻击，随着时间推移塑造智能体行为，无需任何单一的戏剧性漏洞利用。',
    'idea.30.date': '2026年5月',
    'idea.30.cat': 'AI安全',
    'idea.29.title': 'Browser-Use 与 Computer-Use：全新的 AI 攻击面',
    'idea.29.excerpt': '当 AI 智能体能够自主点击、输入并浏览网页时，每一个网站都成为潜在的攻击向量。计算机使用型智能体的威胁模型与基于对话的 AI 截然不同——也危险得多。',
    'idea.29.date': '2026年5月',
    'idea.29.cat': 'AI安全',
    'idea.28.title': '系统提示词提取：攻击者如何窃取你的 LLM 配置',
    'idea.28.excerpt': '系统提示词定义了 LLM 的行为方式——人设、限制、工具和业务逻辑。开发者将其视为机密。攻击者已记录了至少五种可靠的提取技术。通过模糊来保证安全不是安全。',
    'idea.28.date': '2026年5月',
    'idea.28.cat': 'AI安全',
    'idea.27.title': 'OWASP LLM Top 10：实践指南',
    'idea.27.excerpt': 'OWASP LLM 应用 Top 10 从规范到实践的转化：每个类别的真实攻击模式、实际缓解措施，以及面向 AI 产品团队的优先级排序框架。',
    'idea.27.date': '2026年5月',
    'idea.27.cat': 'AI安全',
    'idea.26.title': 'AI 蠕虫：当智能体互相感染',
    'idea.26.excerpt': '自我复制的提示词在多智能体系统中传播，无需任何用户交互。首个 AI 蠕虫已被研究人员验证——本文解析其工作原理，以及为何常规防御手段失效。',
    'idea.26.date': '2026年5月',
    'idea.26.cat': 'AI安全',
    'idea.25.title': '留白并非空白',
    'idea.25.excerpt': '设计中的空白区域不是设计的缺席——它是设计最活跃的成分。负空间控制着你首先看到什么、什么感觉重要，以及某样东西能抓住你注意力多久。移除它，就是移除意义。',
    'idea.25.date': '2026年5月',
    'idea.25.cat': '设计',
    'idea.24.title': 'OAuth 2.0 的智能体问题：当 AI 令牌永不过期',
    'idea.24.excerpt': '代表用户行动的 AI 智能体继承了 OAuth 令牌——而这些令牌往往比任务存活更久、不断积累权限范围，并成为高价值攻击目标。保障现代 Web 安全的授权模型从未为自主智能体而设计，这一差距正在扩大。',
    'idea.24.date': '2026年5月',
    'idea.24.cat': 'Web Security',
    'idea.23.title': '通过工具输出的间接提示注入',
    'idea.23.excerpt': '一种绕过所有系统提示防御的提示注入变体：恶意指令嵌入在工具响应、数据库查询结果和检索的网页内容中——从数据层向上劫持智能体行为。',
    'idea.23.date': '2026年5月',
    'idea.23.cat': 'AI安全',
    'idea.22.title': 'MCP 完整指南：架构原理、服务器构建与实际使用',
    'idea.22.excerpt': '模型上下文协议（MCP）是 Anthropic 将 AI 连接到外部世界的开放标准。本指南涵盖完整内容：MCP 是什么、如何用 TypeScript 和 Python 构建 MCP 服务器、如何接入 Claude Desktop 或 Cursor，以及何时选择 MCP 而非 Skills 等更高层次的替代方案。',
    'idea.22.date': '2026年5月',
    'idea.22.cat': 'AI Development',
    'idea.21.title': 'AI Skills 与 MCP：工作流层 vs 工具层',
    'idea.21.excerpt': 'Skills 和 MCP 都能扩展 AI 智能体的能力，但它们运作在完全不同的层次上。Skills 定义智能体做什么；MCP 定义智能体能访问什么。本文详解如何创建和使用两者，以及为什么通常需要同时使用。',
    'idea.21.date': '2026年5月',
    'idea.21.cat': 'AI Development',
    'idea.20.title': '2026 年 Linux 内核本地提权三部曲：Copy Fail、Dirty Frag 与 Fragnesia',
    'idea.20.excerpt': '2026 年春季，三个严重的 Linux 内核本地提权漏洞相继披露——均在野外被积极利用，均需立即修补。每个 CVE 的详细分析与精确修复步骤。',
    'idea.20.date': '2026年5月',
    'idea.20.cat': 'Zero-Day',
    'idea.19.title': 'NGINX Rift：存在 18 年的重写模块漏洞可实现远程代码执行（CVE-2026-42945）',
    'idea.19.excerpt': '自 2008 年版本 0.6.27 起就潜伏在 nginx 重写模块中的堆缓冲区溢出漏洞于 2026 年 4 月公开披露。CVSS 9.2，无需认证，正被积极利用。所有运行 1.30.0 及以下版本的 nginx 部署均受影响。',
    'idea.19.date': '2026年5月',
    'idea.19.cat': 'Zero-Day',
    'idea.18.title': 'Vibe Coding 隐藏的安全账单',
    'idea.18.excerpt': '使用 AI 编码助手的开发者比以往任何时候都更快地发布功能，也比以往任何时候都更快地发布漏洞。Vibe coding 的安全债务是真实存在的，正在积累，且在暴露之前基本上是不可见的。',
    'idea.18.date': '2025年5月',
    'idea.18.cat': 'AI安全',
    'idea.17.title': 'MCP：没有人预见到的新攻击面',
    'idea.17.excerpt': 'Anthropic 的模型上下文协议（MCP）为 AI 智能体提供了对工具和数据源的持久化、结构化访问。它也给了攻击者一个大多数安全团队尚未建模的新向量——而且领先于它的窗口正在关闭。',
    'idea.17.date': '2025年5月',
    'idea.17.cat': 'AI安全',
    'idea.16.title': '越狱军备竞赛：为什么 AI 安全总是落后',
    'idea.16.excerpt': '部署在大型语言模型中的每一项安全措施都已被绕过。不是某些——是每一个。理解越狱问题在结构上与其他安全问题有何不同，以及这对在敏感场景中部署 AI 的人意味着什么。',
    'idea.16.date': '2025年4月',
    'idea.16.cat': 'AI Safety',
    'idea.15.title': 'DeepSeek 与开源 LLM 安全问题',
    'idea.15.excerpt': 'DeepSeek 的出现迫使 AI 行业正视一个一直在回避的真实对话：部署一个你无法完全审计其训练过程、数据溯源和安全设计的强大 LLM，意味着什么？模型能力差距正在缩小，治理差距却没有。',
    'idea.15.date': '2025年2月',
    'idea.15.cat': 'AI安全',
    'idea.14.title': 'AI 在人类之前发现了 Linux 内核零日漏洞',
    'idea.14.excerpt': '2024 年底，谷歌的 Project Big Sleep 创造了历史：一个 AI 智能体自主发现了 Linux 内核中此前未知的漏洞，并在公开披露前完成了修补。',
    'idea.14.date': '2025年5月',
    'idea.14.cat': 'AI安全',
    'idea.13.title': '提示词注入：AI 无法自我修补的漏洞',
    'idea.13.excerpt': '与缓冲区溢出或 SQL 注入不同，提示词注入攻击是语义层面的——它们利用的是模型遵循指令的本质特性。理解为什么这类漏洞在结构上与以往所有漏洞都有本质区别。',
    'idea.13.date': '2025年5月',
    'idea.13.cat': 'LLM Security',
    'idea.12.title': 'RAG 投毒：当你的 AI 知识库变成攻击向量',
    'idea.12.excerpt': '检索增强生成系统隐式信任其数据源。将对抗性内容注入向量数据库，可以劫持每一次检索到该内容的查询。一次对攻击面的深入解析。',
    'idea.12.date': '2025年4月',
    'idea.12.cat': 'LLM Security',
    'idea.11.title': 'LLM 中的睡眠体：能够在微调后存活的攻击',
    'idea.11.excerpt': 'Anthropic 2024 年的研究表明，LLM 可以被训练成在特定触发条件满足之前表现正常——而标准的 RLHF 安全训练无法消除这种行为。这对任何部署第三方模型的组织意味着什么。',
    'idea.11.date': '2025年4月',
    'idea.11.cat': 'AI Safety',
    'idea.10.title': 'Hugging Face 上的恶意模型：新型供应链攻击',
    'idea.10.excerpt': '研究人员在 Hugging Face Hub 上发现了超过 100 个模型，这些模型包含序列化载荷，可通过 pickle 反序列化在加载时执行任意代码。ML 供应链与 npm 具有相同的漏洞——但受到的审查更少。',
    'idea.10.date': '2025年3月',
    'idea.10.cat': 'Supply Chain',
    'idea.9.title': 'CVE-2024-6387：OpenSSH 中的零日漏洞如何潜伏 18 年未被发现',
    'idea.9.excerpt': 'regreSSHion 是一枚信号弹。这个自 2006 年以来潜伏的竞态条件漏洞，被 Qualys 的 AI 辅助静态分析管道重新发现。关于 AI 驱动的代码审计如何浮现出逃过整整一代人工审查的漏洞。',
    'idea.9.date': '2025年2月',
    'idea.9.cat': 'Zero-Day',
    'idea.8.title': '2025 年 AI 发现的关键漏洞：持续记录',
    'idea.8.excerpt': '从谷歌 Big Sleep 发现的 SQLite 缓冲区溢出，到微软 Security Copilot 标记的 Azure 错误配置——一份记录 AI 发现漏洞、加速修补或改变披露时间线的案例精选。',
    'idea.8.date': '2025年1月',
    'idea.8.cat': 'AI安全',
    'idea.7.title': '反对一致性设计的理由',
    'idea.7.excerpt': '为什么对像素级完美一致性的执念，可能正是让你的产品感觉毫无生气的原因——以及应该追求什么来代替它。',
    'idea.7.date': '2025年5月',
    'idea.7.cat': '设计',
    'idea.6.title': '等宽字体作为美学声明',
    'idea.6.excerpt': '网络上最有趣的角落总是在寻求固定宽度字体，这是有原因的。这不是怀旧——而是一种精准的选择。',
    'idea.6.date': '2025年4月',
    'idea.6.cat': 'Typography',
    'idea.5.title': '速度是一种设计选择',
    'idea.5.excerpt': '性能和美学是同一场对话。3 秒的加载时间不是技术问题——它是信任问题、品牌问题、关系问题。',
    'idea.5.date': '2025年3月',
    'idea.5.cat': 'Performance',
    'idea.4.title': '颗粒感总会回来',
    'idea.4.excerpt': '关于数字界面中质感的复兴，以及为什么一代又一代设计师总是重新发现，最现代的表面从来都不是完美光滑的。',
    'idea.4.date': '2025年2月',
    'idea.4.cat': 'Texture',
    'idea.3.title': '深色模式真正的含义',
    'idea.3.excerpt': '深色模式不是一个无障碍功能，也不是用户偏好切换开关。对我们中的一些人来说，它是唯一诚实的工作方式——一种倾向，而非设置。',
    'idea.3.date': '2025年1月',
    'idea.3.cat': '哲学',
    'idea.2.title': '静态网站与长远考量',
    'idea.2.excerpt': '每个框架都承诺未来。HTML 已经存活了三十年。有些东西值得押注于不需要更新的东西。',
    'idea.2.date': '2024年12月',
    'idea.2.cat': 'Web',
    'idea.1.title': '为什么我总是回归 Georgia',
    'idea.1.excerpt': '为屏幕而生，经过实战检验，比之后出现的任何东西都更具表现力。数字设计史上最被低估的字体，已经在你的设备上了。',
    'idea.1.date': '2024年11月',
    'idea.1.cat': 'Typography',
  },

  ja: {
    'nav.about': 'について', 'nav.work': '作品', 'nav.ideas': 'アイデア', 'nav.contact': 'お問い合わせ',

    'hero.eyebrow': '設立 mmxxv / vsike.com',
    'hero.tagline': '<span class="em">速度。</span>  スタイル。  直感。',
    'hero.sub': 'ビジョンと速度が交差するデジタルアトリエ。デザインと直感が出会い、アイデアが推進力へと変わる場所。',
    'hero.cta1': '空間へ入る  →', 'hero.cta2': '作品を見る',

    'qn.about.desc': 'vsike の物語、理由、そしてビジョン。',
    'qn.work.desc': '厳選されたプロジェクトとデジタル実験。',
    'qn.ideas.desc': '声に出して考える。現場からのノート。',
    'qn.contact.desc': '記憶に残るものを一緒につくりましょう。',

    'phi.label': '哲学',
    'phi.quote': '「速く動く。でも、物事を美しくする細部は決して見失わない。」',
    'phi.p1': 'vsike はシンプルな信念から生まれた。速さと優雅さは対立しない。速度を持って届けながら、同時にピクセルにこだわることができる。経験によって磨かれた直感は、どんなクリエイターにとっても最も鋭いツールだ。',
    'phi.p2': '私たちは無限のノイズの時代に生きている。vsike はシグナルだ——意図的で、熟考された、本当に重要なことへの飽くなき追求。',
    'phi.p3': 'ここにあるすべてのコード、すべての構成、すべての言葉は、その執念の産物だ。それ自体のための完璧さではなく——精度を持った推進力。',
    'phi.cta': 'マニフェストを読む  →',
    'stat.iterations': 'イテレーション', 'stat.direction': '方向性', 'stat.forward': '常に前へ',

    'about.eyebrow': 'vsike について',
    'about.title': 'ビジョン。<br>スタイル。<br>直感。',
    'about.sub': '哲学であり、実践であり、本当に重要なものを作ることへの執着。',
    'manifesto.label': 'マニフェスト',
    'manifesto.intro': 'vsike はスタジオではない。エージェンシーでもない。それはスタンスだ。',
    'manifesto.p1': '実質より速さを重んじる世界で、vsike は両方を追求する。真の速度とは単に速いことではなく、方向性を持つことだ。どこへ向かうのか、なぜ一歩一歩が重要なのかを明確に知ることから生まれる推進力だ。',
    'manifesto.p2': 'スタイルとは、ここでは装飾ではない。可視化された明晰さだ。属さないものをすべて取り除く規律と、本当に必要なものに完全にコミットする勇気。スタイルは世界観——一貫した、認識可能な、獲得されたもの。',
    'manifesto.p3': '直感は？それは最も教えにくく、最も価値のある能力だ。見て、作って、失敗して、また見ることを繰り返す年月から生まれる、本能的な知。vsike はその刃を研ぐために存在する——作品のために、そしてその背後にいるクリエイターのために。',
    'manifesto.p4': '私たちは、最高の仕事は三つが交差するときに生まれると信じている。目指すべき明確なビジョン、それを実現するスタイル、そして到達したときに知ることができる直感。',
    'pillar.v': 'ビジョン', 'pillar.s': 'スタイル', 'pillar.i': '直感',
    'path.label': '歩み',
    'about.cta.text': '私たちが作ったものをご覧になりますか？',
    'about.cta1': '作品を見る  →', 'about.cta2': 'お問い合わせ',

    'work.eyebrow': '厳選作品',
    'work.title': '私たちが<br>作ったもの。',
    'work.sub': 'インターフェース、システム、実験——意図を持って作られたデジタル作品のコレクション。',
    'work.section.label': 'プロジェクト', 'work.section.count': '06 件',
    'work.cta1': 'プロジェクトを始める  →', 'work.cta2.label': '新規案件受付中',

    'ideas.eyebrow': 'アイデア',
    'ideas.title': '声に出して<br>考える。',
    'ideas.sub': 'AIセキュリティ、デザイン、そしてその交差点に関するノート。LLMの脆弱性、ゼロデイ攻撃、長続きするものの作り方について。',
    'ideas.section.label': 'すべての投稿', 'ideas.section.count': '66 件',
    'ideas.loop.label': '最新情報を受け取る',
    'ideas.loop.title': '準備できたら新しいアイデアをお届けします。',
    'ideas.loop.cta': '通知を受け取る  →',

    'contact.eyebrow': 'お問い合わせ',
    'contact.title': '何か作り<br>ましょう。',
    'contact.sub': '新しいプロジェクト、コラボレーション、鋭いアイデア——すべて歓迎します。',
    'contact.direct': '直接連絡', 'contact.elsewhere': 'SNS',
    'contact.available': '新規プロジェクト受付中 — 2025',
    'contact.based': '拠点', 'contact.form.title': 'メッセージを送る',
    'contact.form.name': 'お名前', 'contact.form.email': 'メールアドレス',
    'contact.form.subject': '件名', 'contact.form.message': 'メッセージ',
    'contact.form.submit': '送信する  →', 'contact.form.sent': '送信しました →',
    'contact.placeholder.name': 'お名前',
    'contact.placeholder.subject': '件名は何ですか？',
    'contact.placeholder.message': 'プロジェクト、アイデア、またはご挨拶をお聞かせください。',
    'contact.quote': '「最高のコラボレーションは、本物の問題を持つ人と、それを本当に解決したい人との出会いから始まる。」',
    'contact.link.site.label': 'このサイトについて',
    'contact.link.site': 'スタック、デザインの決断、コロフォン  →',
    'contact.link.careers.label': 'チームに参加',
    'contact.link.careers': 'オープンポジションを見る  →',
    'nav.site': 'このサイト',
    'nav.careers': '採用',
    'nav.privacy': 'プライバシーポリシー',
    'consent.message': 'サイトのトラフィック計測と体験向上のため Cookie を使用しています。詳細は <a href="/privacy.html">プライバシーポリシー</a> をご覧ください。',
    'consent.accept': '同意する',
    'consent.decline': '拒否する',
    'privacy.title': 'プライバシーポリシー',
    'privacy.updated': '最終更新：2026年6月',
    'privacy.intro': 'vsike（以下「当社」）はお客様のプライバシー保護に努めています。本ポリシーでは、収集するデータ、使用方法、およびお客様の権利について説明します。',
    'privacy.s1.title': '収集する情報',
    'privacy.s1.body': 'Google Analytics 4 を通じて匿名の利用データ（ページビュー、セッション時間、参照元、デバイス種別）を収集します。お問い合わせフォームからご連絡いただかない限り、個人を特定できる情報は収集しません。',
    'privacy.s2.title': 'Cookie',
    'privacy.s2.body': '言語設定を記憶するためにファーストパーティ Cookie を使用します。同意いただいた場合、Google Analytics のサードパーティ Cookie（訪問者の行動把握）および Google AdSense の Cookie（関連広告の配信）も使用します。',
    'privacy.s3.title': 'データの利用',
    'privacy.s3.body': '利用データはサイトコンテンツとパフォーマンスの改善にのみ使用します。上記サービスを除き、第三者へのデータの販売・貸与・共有は行いません。',
    'privacy.s4.title': 'お客様の権利（GDPR / CCPA）',
    'privacy.s4.body': 'お客様は、当社が保有するデータへのアクセス、訂正、削除を求める権利があります。ブラウザのローカルストレージを削除することで、いつでも Cookie 同意を撤回できます。カリフォルニア州在住の方：当社は個人情報を販売しません。',
    'privacy.s5.title': 'サードパーティサービス',
    'privacy.s5.body': '当サイトでは Google Analytics 4 および Google AdSense を使用しています。これらのサービスは <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google プライバシーポリシー</a> に従って Cookie を設定し、データを収集する場合があります。',
    'privacy.s6.title': 'お問い合わせ',
    'privacy.s6.body': '本ポリシーについてご不明な点は <a href="mailto:help@vsike.com">help@vsike.com</a> までご連絡ください。',
    'article.back': '← アイデア一覧',
    'idea.66.title': 'AIポストモーテム＆ランブック自動化：3時間から20分へ',
    'idea.66.excerpt': 'AIはポストモーテム執筆を3時間から20分に圧縮し、インシデントタイムラインからランブック初稿を生成できる。正しい部分を自動化し、人間の分析を保ち、将来のインシデントを短縮するポストモーテムコーパスを構築する方法を説明する。',
    'idea.66.date': '2026年5月',
    'idea.66.cat': 'SRE',
    'idea.65.title': 'SREオブザーバビリティのためのMCPツール：エージェントに目を与える',
    'idea.65.excerpt': 'Model Context ProtocolはSREエージェントがElasticsearch、Prometheus、Honeycomb、Kubernetesを自然言語でクエリできるようにする。実際のオブザーバビリティスタックのMCPツール面と、エージェントがすべてを見られるようになったときに何が変わるかを説明する。',
    'idea.65.date': '2026年5月',
    'idea.65.cat': 'SRE',
    'idea.64.title': 'AIエージェントオンコール：アラートから根本原因まで',
    'idea.64.excerpt': 'PagerDutyとAzure SREエージェントは2026年にMTTRを75%削減したと報告している。AI支援オンコールワークフローの構築方法：何を自動化するか、どこで人間をループに保つか、虚偽の信頼の罠を避ける方法。',
    'idea.64.date': '2026年5月',
    'idea.64.cat': 'SRE',
    'idea.63.title': 'カームインターフェース：注意力のためのデザイン',
    'idea.63.excerpt': '2026年のUI界の主流トレンドはマキシマリズムやAIファーストの自動化ではない。それは抑制だ。人間の注意力を尊重し、AIを思慮深いコパイロットとして提示し、ノイズを増幅することを拒否する静かなインターフェース。',
    'idea.63.date': '2026年5月',
    'idea.63.cat': 'デザイン',
    'idea.62.title': 'インターフェースが攻撃面になるとき：ジェネレーティブUIセキュリティ',
    'idea.62.excerpt': 'AI生成インターフェースはダークパターンを幻覚し、XSSペイロードをレンダリングし、WCAGを系統的に違反し得る——悪意からではなく、統計的な妥当性から。UIそのものがモデル出力であるとき、セキュリティモデルはインターフェースを信頼できないものとして扱わなければならない。',
    'idea.62.date': '2026年5月',
    'idea.62.cat': 'AIセキュリティ',
    'idea.61.title': 'エージェントのメモリポイズニング：待ち伏せる攻撃',
    'idea.61.excerpt': 'プロンプトインジェクションは会話が終わると効力を失う。メモリポイズニングはそうではない。MINJA攻撃は95%のインジェクション成功率を達成し、ペイロードは数日から数週間後に適切なクエリが来るまで休眠状態で待機する。',
    'idea.61.date': '2026年5月',
    'idea.61.cat': 'AIセキュリティ',
    'idea.60.title': '2026年のエージェント身元確認：5つの標準、勝者なし',
    'idea.60.excerpt': 'RSAC 2026では、5つの主要ベンダーが同じ週に互換性のないエージェント身元確認フレームワークを発表した。プロトコルの断片化は単なる相互運用性の頭痛ではない——エージェントが通信相手のエージェントのIDを確認できないとき、すべての委任が信頼の前提となる。',
    'idea.60.date': '2026年5月',
    'idea.60.cat': 'AIセキュリティ',
    'idea.59.title': 'マルチホップ委任問題：マルチエージェントシステムのトークンチェーン',
    'idea.59.excerpt': 'エージェントAがエージェントBに委任し、BがエージェントCに委任するとき、最終的なアクションを実際に承認したのは誰か？マルチエージェント委任チェーンは、OAuthが提供するよう設計されたアカウンタビリティモデルを崩壊させている。',
    'idea.59.date': '2026年5月',
    'idea.59.cat': 'AIセキュリティ',
    'idea.58.title': '認可が意図より長生きするとき',
    'idea.58.excerpt': 'エージェント型チャットボットの65%は一度も使用されていないにもかかわらず、有効なアクセス認証情報を保持し続けている。トークンの有効期間は設定の詳細ではない——それは本番稼働中のすべてのエージェントシステムにとっての主要な爆発半径制御だ。',
    'idea.58.date': '2026年5月',
    'idea.58.cat': 'AIセキュリティ',
    'idea.57.title': 'コミュニケーションとしてのデータ可視化',
    'idea.57.excerpt': '凡例がないと解読できないチャートは失敗したチャートだ。最高のデータ可視化は説明なしに主張を伝える——データが語り、デザインは邪魔をしない。',
    'idea.57.date': '2026年5月',
    'idea.57.cat': 'デザイン',
    'idea.56.title': 'アクセシビリティは後付けではない',
    'idea.56.excerpt': '人間の能力の端でデザインすることは制限されたインターフェースを生み出さない——より良いものを生み出す。より明確で、よりシンプルで、より明示的であることを強制するすべてのアクセシビリティの制約は、すべての人の体験を向上させる。',
    'idea.56.date': '2026年5月',
    'idea.56.cat': 'デザイン',
    'idea.55.title': 'ローディング状態はインターフェースのコミュニケーション',
    'idea.55.excerpt': 'スピナーはデザインの決定ではない——それは降伏だ。すべてのローディング状態は、何が起きているかについてユーザーに真実を伝える機会だ。ほとんどのインターフェースはそれを無駄にする。',
    'idea.55.date': '2026年5月',
    'idea.55.cat': 'デザイン',
    'idea.54.title': 'AI駆動のフィッシング：スケールでのソーシャルエンジニアリングツールとしてのLLM',
    'idea.54.excerpt': 'フィッシングはかつて悪い文法と一般的な挨拶で検出可能だった。LLMはその両方のシグナルを排除した——そして今、どんな人間も手動では生産できない規模でのパーソナライズされた、文脈認識のあるソーシャルエンジニアリング攻撃を可能にする。',
    'idea.54.date': '2026年5月',
    'idea.54.cat': 'AIセキュリティ',
    'idea.53.title': 'エージェンティックAI認可：自律システムの権限問題',
    'idea.53.excerpt': 'AIエージェントがファイルの読み取り、メールの送信、またはコードの実行を求めるとき——システムはどのように許可すべきかを決定するか？ほとんどのエージェンティックシステムは、悪用しやすく監査しにくい方法でこれを間違える。',
    'idea.53.date': '2026年5月',
    'idea.53.cat': 'AIセキュリティ',
    'idea.52.title': 'LLMサービス拒否攻撃：トークンフラッディング、スポンジ例、リソース枯渇',
    'idea.52.excerpt': 'LLMはリソース枯渇攻撃に独特に脆弱だ。従来のDoSとは異なり、LLM DoSは一つの慎重に作られたプロンプトで引き起こすことができる——攻撃者はほとんど何も払わないが、防御者はトークンごとに払う。',
    'idea.52.date': '2026年5月',
    'idea.52.cat': 'AIセキュリティ',
    'idea.51.title': 'AIセキュリティインシデント対応：モデルが武器化されたとき',
    'idea.51.excerpt': '侵害されたAIシステムの検知、ダメージの封じ込め、同じ過ちを繰り返さない回復——本番でAIを運用するチームのための実践的プレイブック。',
    'idea.51.date': '2026年5月',
    'idea.51.cat': 'AIセキュリティ',
    'idea.50.title': 'システムプロンプトの強化：LLMアプリケーションの多層防御',
    'idea.50.excerpt': 'システムプロンプトはLLMアプリケーションの最初の防衛ラインであり、最も頻繁に誤設定されるものでもある。インジェクション、抽出、操作に対して強化する方法を解説する。',
    'idea.50.date': '2026年5月',
    'idea.50.cat': 'AIセキュリティ',
    'idea.49.title': 'AIシステムのゼロトラストアーキテクチャ：決して信頼せず、常に検証する',
    'idea.49.excerpt': '従来の境界セキュリティは内部のすべてが安全だと仮定する。AIシステムはすべての層でその仮定を打ち砕く。',
    'idea.49.date': '2026年5月',
    'idea.49.cat': 'AIセキュリティ',
    'idea.48.title': 'AIガバナンスとコンプライアンス：説明責任のあるAIシステムの構築',
    'idea.48.excerpt': 'EU AI法、NIST AI RMF、新興の業界固有の規制がAIを展開する組織に具体的なコンプライアンス義務を作り出している。ガバナンスは単なる文書化ではない——デプロイ後に後付けするのではなく、最初からAIシステムに組み込む必要があるトレーサビリティ、インシデントレスポンス、継続的な監視が必要だ。',
    'idea.48.date': '2026年5月',
    'idea.48.cat': 'AIセキュリティ',
    'idea.47.title': 'LLM APIセキュリティ：レート制限、認証、プロンプト漏洩',
    'idea.47.excerpt': 'LLMをAPI経由で公開すると、従来のWeb APIとは異なるセキュリティ上の懸念が生じる。システムプロンプトの漏洩、コスト枯渇攻撃、トークンベースのレート制限の課題はすべて、標準的なAPIセキュリティがカバーしない専用のアプローチを必要とする。',
    'idea.47.date': '2026年5月',
    'idea.47.cat': 'AIセキュリティ',
    'idea.46.title': 'AI供給チェーンセキュリティ：侵害された重みと汚染されたリポジトリ',
    'idea.46.excerpt': 'AI開発の供給チェーン——HuggingFaceのモデル重み、パブリックリポジトリのデータセット、GitHubのファインチューニングスクリプト——はどんなソフトウェア依存関係チェーンと同様に攻撃可能だ。悪意のある重み、汚染されたデータセット、タイポスクワットされたモデル名がモデルロードの瞬間にコードを実行し、アプリケーションレベルのセキュリティをすべてバイパスする。',
    'idea.46.date': '2026年5月',
    'idea.46.cat': 'AIセキュリティ',
    'idea.45.title': '対抗的入力：AIがないものを見るとき',
    'idea.45.excerpt': '対抗的サンプルは、AIモデルに高い確信度で誤分類を引き起こすよう作られた入力だ——ニューラルネットワークの汎化方法における根本的な脆弱性を明らかにする。ステッカーを貼った一時停止標識が速度制限標識になる。知覚できないピクセルノイズを持つパンダがテナガザルになる。',
    'idea.45.date': '2026年5月',
    'idea.45.cat': 'AIセキュリティ',
    'idea.44.title': 'モデル窃取：APIクエリによる独自AIの抽出',
    'idea.44.excerpt': '十分に動機付けられた攻撃者は、システム的なAPIクエリだけで独自モデルの動作を再構築できる——重みへのアクセスは不要。モデル抽出攻撃はあなたの推論エンドポイントを競合他社のための訓練データソースに変える。',
    'idea.44.date': '2026年5月',
    'idea.44.cat': 'AIセキュリティ',
    'idea.43.title': '訓練データ抽出：公開モデルからプライベートデータを盗む',
    'idea.43.excerpt': 'LLMは訓練データを記憶する——そしてその記憶されたコンテンツは、巧妙に作られたクエリで抽出できる。PII、著作権のあるテキスト、独自のコード、有効なAPIキーがすべて本番のLLMから抽出されている。あなたのデータを知っているモデルはAPIキーを持つすべての人がアクセスできる。',
    'idea.43.date': '2026年5月',
    'idea.43.cat': 'AIセキュリティ',
    'idea.42.title': 'マルチモーダルプロンプトインジェクション：画像に隠された指示',
    'idea.42.excerpt': 'ビジョン言語モデルが画像を処理するとき、その画像は人間に見えない対抗的指示を運べる。レシートの写真、文書スキャン、QRコード——これらすべてが、人間のレビュアーが気づかない方法でモデルの動作を変えるテキストを埋め込める。',
    'idea.42.date': '2026年5月',
    'idea.42.cat': 'AIセキュリティ',
    'idea.41.title': 'デザイントークン：ビジュアルスタイルの唯一の真実の源',
    'idea.41.excerpt': 'デザイントークンはデザインシステムの原子単位だ——デザインツールをプロダクションコードに接続するカラー、スペーシング、タイポグラフィ、モーションの名前付き変数。それなしでは、すべてのチームが同じビジュアル言語の異なる方言を話し、一貫性はスプリントごとに浸食される。',
    'idea.41.date': '2026年5月',
    'idea.41.cat': 'デザイン',
    'idea.40.title': 'フォームデザイン：誰も真剣に考えないインターフェース',
    'idea.40.excerpt': 'フォームはユーザーが作業を行う場所だ。住所を入力し、設定を構成し、支払いを送信し、アカウントを作成する。フォームの質がユーザーがタスクを完了するか放棄するかを決定する——そしてフォームデザインは、コンバージョン率やユーザーの信頼への大きな影響に対して日常的に投資が不足している。',
    'idea.40.date': '2026年5月',
    'idea.40.cat': 'デザイン',
    'idea.39.title': 'モーションデザインの原則：存在する価値のあるアニメーション',
    'idea.39.excerpt': 'インターフェースデザインのモーションには一つの仕事がある：状態変化を知覚可能にすることで認知負荷を減らすこと。それが表すトランジションではなく自分自身に注意を引くアニメーションは、喜びのコスチュームを着たノイズだ。',
    'idea.39.date': '2026年5月',
    'idea.39.cat': 'デザイン',
    'idea.38.title': 'AIレッドチーミング方法論：意図的にモデルを破る',
    'idea.38.excerpt': 'AIシステムのレッドチーミングは従来のソフトウェアとは異なる方法論を必要とする。プロンプトレベルの攻撃、セマンティックエクスプロイト、能力引き出しは既知のCVEにマッピングできない——モデルの決定境界の体系的な探索が必要で、結果はモデルバージョンの変更とともに失効する。',
    'idea.38.date': '2026年5月',
    'idea.38.cat': 'AIセキュリティ',
    'idea.37.title': 'エージェントサンドボックス：本番環境でのAIの封じ込め',
    'idea.37.excerpt': 'ツールアクセスを持つAIエージェントには、従来のプロセス分離をはるかに超えた封じ込め戦略が必要だ。攻撃面にはツール出力経由のプロンプトインジェクション、エージェントチェーン間の能力エスカレーション、一見無害なAPIコール経由のデータ漏洩が含まれる。',
    'idea.37.date': '2026年5月',
    'idea.37.cat': 'AIセキュリティ',
    'idea.36.title': 'LLMファインチューニングセキュリティ：訓練で埋め込むバックドア',
    'idea.36.excerpt': 'ファインチューニングは基盤モデルをドメインに適応させる——そして元の安全訓練が防ぐように設計された行動を密かに持ち込む可能性がある。バックドアトリガー、アライメント破壊サンプル、汚染データセットすべてがファインチューニングパイプラインを通じて侵入し、本番でトリガーが発火するまで見えない。',
    'idea.36.date': '2026年5月',
    'idea.36.cat': 'AIセキュリティ',
    'idea.35.title': 'AI支援ソーシャルエンジニアリング：ディープフェイク、音声クローン、大規模スピアフィッシング',
    'idea.35.excerpt': 'AIは個人化された欺瞞のコストを崩壊させた。音声クローニングは3秒の音声でわずか数セント。リアルタイムのディープフェイク動画は家庭用ハードウェアで動作する。エンタープライズ規模のスピアフィッシングは技術的に些細なことになった。',
    'idea.35.date': '2026年5月',
    'idea.35.cat': 'AIセキュリティ',
    'idea.34.title': 'LLMハルシネーションセキュリティベクターとして',
    'idea.34.excerpt': 'ハルシネーションされたパッケージ名がインストールされる。ハルシネーションされたURLが訪問される。ハルシネーションされたコードが本番環境にデプロイされる。AIが自信を持って捏造するとき、下流の損害は現実だ。',
    'idea.34.date': '2026年5月',
    'idea.34.cat': 'AIセキュリティ',
    'idea.33.title': 'エラーステート：失敗のためのデザイン',
    'idea.33.excerpt': 'ほとんどのデザインシステムは成功のために設計されている。エラーステートは後付け——曖昧で、責任転嫁し、役に立たない。フラストレーションを与えるプロダクトと信頼を勝ち取るプロダクトの差は、ここにあることが多い。',
    'idea.33.date': '2026年5月',
    'idea.33.cat': 'デザイン',
    'idea.32.title': 'カラーシステム：パレットを超えて',
    'idea.32.excerpt': 'パレットは色のコレクションだ。カラーシステムは、色がどう関連し、どこで使われるかについてのルールセットだ。ほとんどのプロダクトはパレットを持っている。システムを持つものはほとんどいない。',
    'idea.32.date': '2026年5月',
    'idea.32.cat': 'デザイン',
    'idea.31.title': 'タイポグラフィ階層：視覚的重みが目を導く方法',
    'idea.31.excerpt': '階層はタイポグラファーの文法だ。それなしでは、ページは群衆だ。それがあれば、目はどこへ行くべきか、どの順序でかを正確に知る——読者がまったく考える必要なく。',
    'idea.31.date': '2026年5月',
    'idea.31.cat': 'デザイン',
    'idea.30.title': 'AIエージェントにおけるメモリポイズニング',
    'idea.30.excerpt': '永続的メモリを持つAIエージェントは強力だ。しかし同時に、メモリポイズニングに対して固有の脆弱性を持つ——単一の劇的な悪用なしに、時間をかけてエージェントの行動を形成する、遅く隠密な攻撃だ。',
    'idea.30.date': '2026年5月',
    'idea.30.cat': 'AIセキュリティ',
    'idea.29.title': 'Browser-Use & Computer-Use：新しいAI攻撃面',
    'idea.29.excerpt': 'AIエージェントが自律的にクリック、入力、ブラウジングできるとき、すべてのウェブサイトが潜在的な攻撃ベクターになる。コンピューター使用エージェントの脅威モデルはチャットベースのAIとは根本的に異なり、はるかに危険だ。',
    'idea.29.date': '2026年5月',
    'idea.29.cat': 'AIセキュリティ',
    'idea.28.title': 'システムプロンプト抽出：攻撃者はどうやってLLM設定を盗むか',
    'idea.28.excerpt': 'システムプロンプトはLLMの動作を定義する——ペルソナ、制約、ツール、ビジネスロジック。開発者はそれを秘密として扱う。攻撃者は少なくとも5つの信頼できる抽出技術を記録している。難読化によるセキュリティは本当のセキュリティではない。',
    'idea.28.date': '2026年5月',
    'idea.28.cat': 'AIセキュリティ',
    'idea.27.title': 'OWASP LLM Top 10：実践フィールドガイド',
    'idea.27.excerpt': 'OWASP LLMアプリケーションTop 10を仕様から実践へ。各カテゴリの実際の攻撃パターン、実際の緩和策、およびAI製品を出荷するチームのための優先順位付けフレームワーク。',
    'idea.27.date': '2026年5月',
    'idea.27.cat': 'AIセキュリティ',
    'idea.26.title': 'AIワーム：エージェントが互いに感染するとき',
    'idea.26.excerpt': 'ユーザーの操作なしにマルチエージェントシステムを伝播する自己複製プロンプト。最初のAIワームはすでに実証済み——その仕組みと、なぜ標準的な防御が機能しないかを解説します。',
    'idea.26.date': '2026年5月',
    'idea.26.cat': 'AIセキュリティ',
    'idea.25.title': '余白は空ではない',
    'idea.25.excerpt': 'デザインの空白部分はデザインの不在ではなく、最も活発な要素だ。ネガティブスペースは何を最初に見るか、何が重要に感じるか、何がどれだけ長く注意を引き付けるかを制御する。それを取り除くことは意味を取り除くことだ。',
    'idea.25.date': '2026年5月',
    'idea.25.cat': 'デザイン',
    'idea.24.title': 'OAuth 2.0のエージェント問題：AIトークンが永遠に生き続けるとき',
    'idea.24.excerpt': 'ユーザーの代わりに行動するAIエージェントはOAuthトークンを引き継ぎます——そのトークンはタスクよりも長く生き残り、スコープを蓄積し、高価値の攻撃ターゲットになることが多い。現代のウェブを守る認可モデルは自律エージェント向けに設計されておらず、そのギャップは拡大しています。',
    'idea.24.date': '2026年5月',
    'idea.24.cat': 'Web Security',
    'idea.23.title': 'ツール出力経由の間接プロンプトインジェクション',
    'idea.23.excerpt': 'あらゆるシステムプロンプト防御を回避するプロンプトインジェクションの亜種：ツールレスポンス、データベースクエリ結果、取得したウェブコンテンツ内に埋め込まれた悪意ある指示——データ層からエージェントの動作を乗っ取る。',
    'idea.23.date': '2026年5月',
    'idea.23.cat': 'AIセキュリティ',
    'idea.22.title': 'MCP完全ガイド：アーキテクチャ、サーバー構築、実際の活用',
    'idea.22.excerpt': 'Model Context Protocol（MCP）はAnthropicがAIを外部世界に接続するためのオープンスタンダードだ。このガイドでは全体像をカバーする：MCPが何であり何ではないか、TypeScriptとPythonでMCPサーバーを構築する方法、Claude DesktopやCursorに接続する方法、そしてSkillsなどの高レベルな代替手段よりもMCPが適切な選択となる場合。',
    'idea.22.date': '2026年5月',
    'idea.22.cat': 'AI Development',
    'idea.21.title': 'AI SkillsとMCP：ワークフロー層 vs ツール層',
    'idea.21.excerpt': 'SkillsとMCPはどちらもAIエージェントを拡張しますが、完全に異なる層で動作します。Skillsはエージェントが何をするかを定義し、MCPはエージェントが何にアクセスできるかを定義します。両方の作成方法と使用方法、そしてなぜ通常は両方が必要なのかを解説します。',
    'idea.21.date': '2026年5月',
    'idea.21.cat': 'AI Development',
    'idea.20.title': '2026年Linuxカーネル特権昇格三部作：Copy Fail、Dirty Frag、Fragnesia',
    'idea.20.excerpt': '2026年春、3つの重大なLinuxカーネルローカル特権昇格脆弱性が相次いで明らかになった——すべて野外で積極的に悪用されており、即時パッチ適用が必要。各CVEの詳細分析と正確な修正手順。',
    'idea.20.date': '2026年5月',
    'idea.20.cat': 'Zero-Day',
    'idea.19.title': 'NGINX Rift：18年間潜伏したRewriteモジュールの欠陥がRCEを可能に（CVE-2026-42945）',
    'idea.19.excerpt': '2008年のバージョン0.6.27以降、nginxのrewriteモジュールに潜伏していたヒープバッファオーバーフローが2026年4月に公開された。CVSS 9.2。認証不要。積極的に悪用中。1.30.0以前を実行するすべてのnginx展開が影響を受ける。',
    'idea.19.date': '2026年5月',
    'idea.19.cat': 'Zero-Day',
    'idea.18.title': 'バイブコーディングの隠れたセキュリティ請求書',
    'idea.18.excerpt': 'AIコーディングアシスタントを使う開発者はかつてないほど速く機能を出荷している。同時に、かつてないほど速く脆弱性も出荷している。バイブコーディングのセキュリティ負債は現実であり、蓄積されており、露見するまでほぼ見えない。',
    'idea.18.date': '2025年5月',
    'idea.18.cat': 'AIセキュリティ',
    'idea.17.title': 'MCP：誰も予見しなかった新しい攻撃面',
    'idea.17.excerpt': 'AnthropicのModel Context ProtocolはAIエージェントにツールとデータソースへの持続的で構造化されたアクセスを与える。また、ほとんどのセキュリティチームがまだモデル化していない新しいベクターを攻撃者に与える——そして先手を打つ窓は閉じつつある。',
    'idea.17.date': '2025年5月',
    'idea.17.cat': 'AIセキュリティ',
    'idea.16.title': 'ジェイルブレイク軍拡競争：なぜAI安全は常に後れを取るのか',
    'idea.16.excerpt': '大規模言語モデルに展開されたすべての安全対策が突破されてきた。一部ではなく——すべてが。ジェイルブレイク問題が他のセキュリティ問題と構造的にどう異なるのか、そしてそれが敏感なコンテキストでAIを展開する人にとって何を意味するのかを理解する。',
    'idea.16.date': '2025年4月',
    'idea.16.cat': 'AI Safety',
    'idea.15.title': 'DeepSeekとオープンソースLLMセキュリティ問題',
    'idea.15.excerpt': 'DeepSeekの登場は、AI業界が避けてきた本当の会話を強いた：トレーニングプロセス、データの出所、安全設計を完全に監査できない強力なLLMを展開するとはどういう意味か？モデル能力のギャップは縮まっている。ガバナンスのギャップは縮まっていない。',
    'idea.15.date': '2025年2月',
    'idea.15.cat': 'AIセキュリティ',
    'idea.14.title': 'AIが人間より先にLinuxカーネルのゼロデイを発見',
    'idea.14.excerpt': '2024年末、GoogleのProject Big Sleepは歴史を作った。AIエージェントがLinuxカーネルの未知の脆弱性を自律的に発見し、公開開示前にパッチが当てられたのだ。',
    'idea.14.date': '2025年5月',
    'idea.14.cat': 'AIセキュリティ',
    'idea.13.title': 'プロンプトインジェクション：AIが自分でパッチを当てられない脆弱性',
    'idea.13.excerpt': 'バッファオーバーフローやSQLインジェクションとは異なり、プロンプトインジェクション攻撃はセマンティックだ——モデルの指示追従という本質的な性質を悪用する。このクラスの脆弱性がこれまでのあらゆるものと構造的にどう違うのかを理解する。',
    'idea.13.date': '2025年5月',
    'idea.13.cat': 'LLM Security',
    'idea.12.title': 'RAGポイズニング：AIナレッジベースが攻撃ベクターになるとき',
    'idea.12.excerpt': 'Retrieval-Augmented Generationシステムはデータソースを暗黙的に信頼する。ベクターデータベースに敵対的コンテンツを注入すると、それを検索するすべてのクエリを乗っ取ることができる。攻撃面の解説。',
    'idea.12.date': '2025年4月',
    'idea.12.cat': 'LLM Security',
    'idea.11.title': 'LLMのスリーパーエージェント：ファインチューニングを生き延びる攻撃',
    'idea.11.excerpt': 'Anthropicの2024年の研究は、LLMが特定のトリガー条件が満たされるまで正常に動作するように訓練できることを示した——そして標準的なRLHF安全トレーニングはその動作を除去できない。サードパーティモデルを展開するあらゆる組織にとっての意味。',
    'idea.11.date': '2025年4月',
    'idea.11.cat': 'AI Safety',
    'idea.10.title': 'Hugging Faceの悪意あるモデル：新しいサプライチェーン攻撃',
    'idea.10.excerpt': '研究者たちはHugging Face Hubで、pickleデシリアライゼーションを通じてロード時に任意コードを実行するシリアライズペイロードを含む100以上のモデルを発見した。MLサプライチェーンはnpmと同じ脆弱性を持つ——そしてより少ない監視しか受けていない。',
    'idea.10.date': '2025年3月',
    'idea.10.cat': 'Supply Chain',
    'idea.9.title': 'CVE-2024-6387：OpenSSHのゼロデイが18年間検出されなかった理由',
    'idea.9.excerpt': 'regreSSHionはシグナル弾だった。2006年から潜伏していた競合状態の脆弱性が、QualysのAI支援静的解析パイプラインによって再発見された。AIを活用したコード監査が、一世代の手動レビューを逃れたバグをどのように発見しているか。',
    'idea.9.date': '2025年2月',
    'idea.9.cat': 'Zero-Day',
    'idea.8.title': '2025年のAI発見の重大脆弱性：進行中の集計',
    'idea.8.excerpt': 'GoogleのBig SleepによるSQLiteバッファオーバーフローから、MicrosoftのSecurity CopilotによるAzureの設定ミスのフラグまで——AIがバグを発見したか、パッチを加速したか、開示のタイムラインを変えた脆弱性の厳選ログ。',
    'idea.8.date': '2025年1月',
    'idea.8.cat': 'AIセキュリティ',
    'idea.7.title': '一貫性デザインへの異議',
    'idea.7.excerpt': 'ピクセルパーフェクトな一貫性への執着が、あなたのプロダクトを生気のないものにしているかもしれない理由——そして代わりに何を目指すべきか。',
    'idea.7.date': '2025年5月',
    'idea.7.cat': 'デザイン',
    'idea.6.title': '美学的声明としての等幅フォント',
    'idea.6.excerpt': 'ウェブの最も興味深い領域が固定幅フォントを求め続けるのには理由がある。ノスタルジーではない——精度の追求だ。',
    'idea.6.date': '2025年4月',
    'idea.6.cat': 'Typography',
    'idea.5.title': 'スピードはデザインの選択だ',
    'idea.5.excerpt': 'パフォーマンスと美学は同じ会話だ。3秒のロード時間は技術的な問題ではない——信頼の問題、ブランドの問題、関係の問題だ。',
    'idea.5.date': '2025年3月',
    'idea.5.cat': 'Performance',
    'idea.4.title': 'グレインは必ず戻ってくる',
    'idea.4.excerpt': 'デジタルインターフェースにおけるテクスチャの復活について、そして世代を超えてデザイナーたちが最もモダンな表面は決して完璧に滑らかではないと再発見し続ける理由について。',
    'idea.4.date': '2025年2月',
    'idea.4.cat': 'Texture',
    'idea.3.title': 'ダークモードが実際に意味するもの',
    'idea.3.excerpt': 'ダークモードはアクセシビリティ機能でもユーザー設定トグルでもない。私たちの一部にとっては、それが唯一の正直な働き方だ——設定ではなく、傾向だ。',
    'idea.3.date': '2025年1月',
    'idea.3.cat': '哲学',
    'idea.2.title': '静的サイトと長期戦略',
    'idea.2.excerpt': 'すべてのフレームワークは未来を約束する。HTMLはすでに30年生き延びた。更新を必要としないものに賭けることには、何か言うべきことがある。',
    'idea.2.date': '2024年12月',
    'idea.2.cat': 'Web',
    'idea.1.title': 'なぜ私はGeorgiaに戻り続けるのか',
    'idea.1.excerpt': 'スクリーンネイティブで、実戦でテスト済みで、その後に来たどんなものよりも表現力豊か。デジタルデザインの歴史で最も過小評価されている書体は、すでにあなたのデバイスに入っている。',
    'idea.1.date': '2024年11月',
    'idea.1.cat': 'Typography',
  }
};

/* Merge article-specific translations when present (inline script on detail pages) */
if (window.ARTICLE_TRANS) {
  ['en', 'zh', 'ja'].forEach(lang => {
    if (LANG[lang] && window.ARTICLE_TRANS[lang]) {
      Object.assign(LANG[lang], window.ARTICLE_TRANS[lang]);
    }
  });
}

/* ─── Apply Language ─────────────────────────────────────────────── */
function applyLang(lang) {
  if (!LANG[lang]) return;
  const t = LANG[lang];

  document.documentElement.lang = lang;
  localStorage.setItem('vsike-lang', lang);

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const v = t[el.dataset.i18n];
    if (v !== undefined) el.textContent = v;
  });
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const v = t[el.dataset.i18nHtml];
    if (v !== undefined) el.innerHTML = v;
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const v = t[el.dataset.i18nPlaceholder];
    if (v !== undefined) el.placeholder = v;
  });

  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
    btn.setAttribute('aria-pressed', btn.dataset.lang === lang ? 'true' : 'false');
  });
}

/* Language switcher clicks */
document.addEventListener('click', e => {
  const btn = e.target.closest('.lang-btn');
  if (btn && btn.dataset.lang) applyLang(btn.dataset.lang);
});

/* Init on page load */
const initLang = localStorage.getItem('vsike-lang') || 'en';
applyLang(initLang);

/* ─── Navigation Scroll State ────────────────────────────────────── */
(function () {
  const nav = document.querySelector('.nav');
  if (!nav) return;
  const update = () => nav.classList.toggle('scrolled', window.scrollY > 40);
  update();
  window.addEventListener('scroll', update, { passive: true });
})();

/* ─── Mobile Nav ─────────────────────────────────────────────────── */
(function () {
  const toggle = document.querySelector('.nav-toggle');
  const mobile = document.querySelector('.nav-mobile');
  if (!toggle || !mobile) return;

  toggle.addEventListener('click', () => {
    const open = toggle.classList.toggle('open');
    mobile.classList.toggle('open', open);
    toggle.setAttribute('aria-expanded', String(open));
    document.body.style.overflow = open ? 'hidden' : '';
  });

  mobile.querySelectorAll('a').forEach(a => {
    a.addEventListener('click', () => {
      toggle.classList.remove('open');
      mobile.classList.remove('open');
      toggle.setAttribute('aria-expanded', 'false');
      document.body.style.overflow = '';
    });
  });
})();

/* ─── Active Nav Link ─────────────────────────────────────────────── */
(function () {
  const page = window.location.pathname.split('/').pop() || 'index.html';
  document.querySelectorAll('.nav-links a').forEach(a => {
    if (a.getAttribute('href') === page) a.classList.add('active');
  });
})();

/* ─── Page Transition ─────────────────────────────────────────────── */
(function () {
  const curtain = document.querySelector('.page-transition');
  if (!curtain) return;

  curtain.classList.add('entering');
  curtain.addEventListener('animationend', () => {
    curtain.classList.remove('entering');
    curtain.style.transform = 'translateY(-100%)';
    triggerAboveFold();
  }, { once: true });

  document.addEventListener('click', e => {
    const link = e.target.closest('a[href]');
    if (!link) return;
    const href = link.getAttribute('href');
    if (!href || href.startsWith('#') || href.startsWith('mailto:') || href.startsWith('tel:') || href.startsWith('http')) return;
    e.preventDefault();
    curtain.style.transform = '';
    curtain.classList.add('leaving');
    curtain.addEventListener('animationend', () => { window.location = href; }, { once: true });
  });
})();

/* ─── Scroll Reveal ───────────────────────────────────────────────── */
(function () {
  const items = document.querySelectorAll('.reveal');
  if (!items.length) return;

  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.08, rootMargin: '0px 0px -40px 0px' });

  items.forEach(el => observer.observe(el));
})();

function triggerAboveFold() {
  document.querySelectorAll('.hero .reveal, .page-hero .reveal').forEach((el, i) => {
    setTimeout(() => el.classList.add('visible'), i * 140);
  });
}

/* ─── Cookie Consent ──────────────────────────────────────────────── */
(function () {
  const STORAGE_KEY = 'vsike_consent';

  function grantAnalytics() {
    if (typeof gtag === 'function') {
      gtag('consent', 'update', { analytics_storage: 'granted', ad_storage: 'granted' });
    }
  }

  function buildBanner() {
    const lang = localStorage.getItem('vsike-lang') || 'en';
    const t = LANG[lang] || LANG.en;

    const bar = document.createElement('div');
    bar.className = 'consent-bar';
    bar.id = 'consent-bar';
    bar.setAttribute('role', 'region');
    bar.setAttribute('aria-label', 'Cookie consent');

    const p = document.createElement('p');
    p.innerHTML = t['consent.message'] || 'We use cookies to improve your experience. <a href="/privacy.html">Privacy Policy</a>.';
    bar.appendChild(p);

    const actions = document.createElement('div');
    actions.className = 'consent-actions';

    const decline = document.createElement('button');
    decline.className = 'consent-btn consent-btn-decline';
    decline.textContent = t['consent.decline'] || 'Decline';
    decline.addEventListener('click', () => {
      localStorage.setItem(STORAGE_KEY, 'declined');
      hide();
    });

    const accept = document.createElement('button');
    accept.className = 'consent-btn consent-btn-accept';
    accept.textContent = t['consent.accept'] || 'Accept';
    accept.addEventListener('click', () => {
      localStorage.setItem(STORAGE_KEY, 'accepted');
      grantAnalytics();
      hide();
    });

    actions.appendChild(decline);
    actions.appendChild(accept);
    bar.appendChild(actions);
    document.body.appendChild(bar);

    function hide() {
      bar.classList.add('consent-hidden');
      setTimeout(() => bar.remove(), 350);
    }
  }

  const stored = localStorage.getItem(STORAGE_KEY);
  if (stored === 'accepted') {
    grantAnalytics();
  } else if (!stored) {
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', buildBanner);
    } else {
      buildBanner();
    }
  }
})();

/* ─── Contact Form ────────────────────────────────────────────────── */
(function () {
  const form = document.querySelector('.contact-form');
  if (!form) return;
  form.addEventListener('submit', e => {
    e.preventDefault();
    const btn = form.querySelector('button[type=submit]');
    if (!btn) return;
    const original = btn.innerHTML;
    const lang = localStorage.getItem('vsike-lang') || 'en';
    btn.innerHTML = LANG[lang]['contact.form.sent'] || 'Sent →';
    btn.disabled = true;
    setTimeout(() => { btn.innerHTML = original; btn.disabled = false; }, 3000);
  });
})();
